backEnd_src/backEnd_main.c File Reference
user call for whatDown chat app. server (back end) side.
#include `defines.h`
*
#include `whatDownBackEndApp.h`
*
Functions
int main (int argc, char *argv[])
Detailed Description
user call for whatDown chat app. server (back end) side.
Date
Jul 4, 2017
Author
Yuval Hamberg
Copyright
MIT
Function Documentation
int main (int argc, char * argv[])
Definition at line 14 of file backEnd_main.c.
References GEN_ERROR, WhatDownBackEndApp_Create(), WhatDownBackEndApp_Destroy(), and WhatDownBackEndApp_Run().