frontEnd_src/client_userInput.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include `defines.h`
*
#include `Protocol.h`
*
#include `tcp_client.h`
*
Macros
#define MAX_MSG_SIZE 1024
#define NDBUG /* remove for debug */
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
#define MAX_MSG_SIZE 1024
Definition at line 16 of file client_userInput.c.
Referenced by main().
#define NDBUG /* remove for debug */
Definition at line 17 of file client_userInput.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 20 of file client_userInput.c.
References ClientReceiveMessage::m_messageType, ClientReceiveMessage::m_status, MAX_MSG_SIZE, Protocol_DecodeClient(), Protocol_EncodeSignUp(), sanity_check(), TCP_ClientRecive(), TCP_ClientSend(), TCP_CreateClient(), TCP_DestroyClient(), and TRUE.