frontEnd_src/client_WhatDownApp_main.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include `defines.h`
*
#include `ClientWhatDownApp.h`
*
Macros
#define MAX_MSG_SIZE 1024
#define IP_LENGTH 16
#define PORT_LENGTH 6
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
#define IP_LENGTH 16
Definition at line 18 of file client_WhatDownApp_main.c.
Referenced by main().
#define MAX_MSG_SIZE 1024
Definition at line 17 of file client_WhatDownApp_main.c.
#define PORT_LENGTH 6
Definition at line 19 of file client_WhatDownApp_main.c.
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 23 of file client_WhatDownApp_main.c.
References GEN_ERROR, IP_LENGTH, PORT_LENGTH, sanity_check(), WhatDownClientApp_Create(), WhatDownClientApp_Destroy(), and WhatDownClientApp_Run().