frontEnd_src/ClientWhatDownApp.h File Reference
the front file for WhatDown Chat App front end (client side).
#include `defines.h`
*
Typedefs
typedef struct WhatDownClientApp WhatDownClientApp_t
Functions
WhatDownClientApp_t * WhatDownClientApp_Create (const char *_serverIP, uint _serverPort)
create and setup the module
void WhatDownClientApp_Destroy (WhatDownClientApp_t *_appBE)
clean up after the processing
bool WhatDownClientApp_Run (WhatDownClientApp_t *_appBE)
activate the components of the client. for example the ui.
bool WhatDownClientApp_Stop (WhatDownClientApp_t *_appBE)
stops the client run. does not disconnect.
Detailed Description
the front file for WhatDown Chat App front end (client side).
Date
Jul 16, 2017
Author
Yuval Hamberg
Typedef Documentation
typedef struct WhatDownClientApp WhatDownClientApp_t
Definition at line 21 of file ClientWhatDownApp.h.
Function Documentation
WhatDownClientApp_t* WhatDownClientApp_Create (const char * _serverIP, uint _serverPort)
create and setup the module
Parameters
_serverIP the server address to connect to. format of XXX.XXX.XXX.XXX
_serverPort the server port to connect to.
Returns
a pointer to the module struct
Definition at line 36 of file ClientWhatDownApp.c.
References LogicFE_Create(), WhatDownClientApp::m_logicFE, WhatDownClientApp::m_magicNumber, WhatDownClientApp::m_server, WhatDownClientApp::m_UI, MAGIC_NUMBER_ALIVE_CLIENT_APP, TCP_CreateClient(), and UI_Create().
Referenced by main().
void WhatDownClientApp_Destroy (WhatDownClientApp_t * _appBE)
clean up after the processing
Parameters
_appBE the pointer to the struct
Definition at line 71 of file ClientWhatDownApp.c.
Referenced by main().
bool WhatDownClientApp_Run (WhatDownClientApp_t * _appBE)
activate the components of the client. for example the ui.
Parameters
_appBE the pointer to the struct
Returns
TRUE for success. FALSE for error return.
Definition at line 76 of file ClientWhatDownApp.c.
References WhatDownClientApp::m_UI, TRUE, and Ui_Run().
Referenced by main().
bool WhatDownClientApp_Stop (WhatDownClientApp_t * _appBE)
stops the client run. does not disconnect.
Parameters
_appBE the pointer to the struct
Returns
TRUE for success. FALSE for error return.
Definition at line 85 of file ClientWhatDownApp.c.
References FALSE.