frontEnd_src/Client_ui.h File Reference
#include `defines.h`
*
Typedefs
typedef struct Client_UI Client_UI
typedef struct Logic_FE Logic_FE_t
Functions
Client_UI * UI_Create (Logic_FE_t *_frontEnd)
create and setup the ui
void Ui_Destroy (Client_UI *_ui)
destroy and clean up after
void Ui_Run (Client_UI *_ui)
start the loop of the UI
void Ui_Stop (Client_UI *_ui)
stop the loop of the UI. wont happen immediately.
Typedef Documentation
typedef struct Client_UI Client_UI
Definition at line 17 of file Client_ui.h.
typedef struct Logic_FE Logic_FE_t
Definition at line 18 of file Client_ui.h.
Function Documentation
Client_UI* UI_Create (Logic_FE_t * _frontEnd)
create and setup the ui
Parameters
_frontEnd a pointer to the FrontEnd-logic. in order to send requsts to.
Returns
a pointer to the new struct
Definition at line 39 of file Client_ui.c.
References Client_UI::m_logicFE.
Referenced by WhatDownClientApp_Create().
void Ui_Destroy (Client_UI * _ui)
destroy and clean up after
Parameters
_ui the pointer to the struct
void Ui_Run (Client_UI * _ui)
start the loop of the UI
Parameters
_ui the pointer to the struct
Definition at line 55 of file Client_ui.c.
References CreateNewGroupFunction(), DeleteUserFunction(), DisconnectFunction(), FALSE, GetAllGruopFunction(), JoinGruopFunction(), LeaveGroupFunction(), LoginFunction(), LogoutFunction(), SignupFunction(), and TRUE.
Referenced by WhatDownClientApp_Run().
void Ui_Stop (Client_UI * _ui)
stop the loop of the UI. wont happen immediately.
Parameters
_ui the pointer to the struct