frontEnd_src/Client_ui.c File Reference
#include <stdlib.h>
*
#include <stdio.h>
*
#include <string.h>
*
#include `Client_ui.h`
*
#include `logicFE.h`
*
#include `Protocol.h`
*
#include `defines.h`
*
Data Structures
struct Client_UI
Functions
int SignupFunction (Client_UI *_ui)
int LoginFunction (Client_UI *_ui)
void LogoutFunction (Client_UI *_ui)
void DisconnectFunction (Client_UI *_ui)
void DeleteUserFunction (Client_UI *_ui)
void CreateNewGroupFunction (Client_UI *_ui)
void JoinGruopFunction (Client_UI *_ui)
void LeaveGroupFunction (Client_UI *_ui)
void GetAllGruopFunction (Client_UI *_ui)
Client_UI * UI_Create (Logic_FE_t *_frontEnd)
create and setup the ui
void Ui_Run (Client_UI *_ui)
start the loop of the UI
Function Documentation
void CreateNewGroupFunction (Client_UI * _ui)
Definition at line 278 of file Client_ui.c.
References LogicFE_CreateGroup(), Client_UI::m_logicFE, and MAX_GROUP_NAME.
Referenced by Ui_Run().
void DeleteUserFunction (Client_UI * _ui)
Definition at line 274 of file Client_ui.c.
Referenced by Ui_Run().
void DisconnectFunction (Client_UI * _ui)
Definition at line 270 of file Client_ui.c.
Referenced by Ui_Run().
void GetAllGruopFunction (Client_UI * _ui)
Definition at line 325 of file Client_ui.c.
References BackEnd_CLIENT_DISCONNECTED, BackEnd_GROUP_DO_NOT_EXIST, BackEnd_GROUP_NAME_INVALID, BackEnd_GROUP_NAME_TAKEN, BackEnd_MORE_INFO_INCOMING, BackEnd_NO_FREE_IP, BackEnd_PASSWORD_INVALID, BackEnd_REQUST_UNKNOWN, BackEnd_SUCCESS, BackEnd_SYSTEM_FAIL, BackEnd_UNKNOWN_ERROR, BackEnd_USER_NAME_INVALID, BackEnd_USER_NAME_TAKEN, BackEnd_USER_NOT_FOUND, FALSE, LogicFE_GetAllGroupsName(), Client_UI::m_logicFE, sanity_check(), and TRUE.
Referenced by Ui_Run().
void JoinGruopFunction (Client_UI * _ui)
Definition at line 298 of file Client_ui.c.
References LogicFE_JoinGroup(), Client_UI::m_logicFE, and MAX_GROUP_NAME.
Referenced by Ui_Run().
void LeaveGroupFunction (Client_UI * _ui)
Definition at line 321 of file Client_ui.c.
Referenced by Ui_Run().
int LoginFunction (Client_UI * _ui)
Definition at line 237 of file Client_ui.c.
References BackEnd_SUCCESS, FALSE, LogicFE_Login(), Client_UI::m_logicFE, MAX_GROUP_NAME, MAX_PASSWORD, MAX_USERNAME, and TRUE.
Referenced by Ui_Run().
void LogoutFunction (Client_UI * _ui)
Definition at line 266 of file Client_ui.c.
Referenced by Ui_Run().
int SignupFunction (Client_UI * _ui)
Definition at line 208 of file Client_ui.c.
References BackEnd_SUCCESS, FALSE, LogicFE_Signup(), Client_UI::m_logicFE, MAX_GROUP_NAME, MAX_PASSWORD, MAX_USERNAME, and TRUE.
Referenced by Ui_Run().
Client_UI* UI_Create (Logic_FE_t * _frontEnd)
create and setup the ui
Parameters
_frontEnd a pointer to the FrontEnd-logic. in order to send requsts to.
Returns
a pointer to the new struct
Definition at line 39 of file Client_ui.c.
References Client_UI::m_logicFE.
Referenced by WhatDownClientApp_Create().
void Ui_Run (Client_UI * _ui)
start the loop of the UI
Parameters
_ui the pointer to the struct
Definition at line 55 of file Client_ui.c.
References CreateNewGroupFunction(), DeleteUserFunction(), DisconnectFunction(), FALSE, GetAllGruopFunction(), JoinGruopFunction(), LeaveGroupFunction(), LoginFunction(), LogoutFunction(), SignupFunction(), and TRUE.
Referenced by WhatDownClientApp_Run().