src/defines.c File Reference
#include `defines.h`
*
Functions
void sanity_check (char *_string, uint _size, char _replaceWith)
Function Documentation
void sanity_check (char * _string, uint _size, char _replaceWith)
Definition at line 10 of file defines.c.
Referenced by GetAllGruopFunction(), main(), TCP_ClientRecive(), and TCP_Recive().