backEnd_src/groupsHandle.c File Reference
#include <string.h>
*
#include `groupsHandle.h`
*
#include `hashmap.h`
*
#include `Protocol.h`
*
Data Structures
struct GroupHandel
struct GroupUnit
Macros
#define MAGIC_NUMBER_GRP_HNDL 0xdeadface
#define MAGIC_NUMBER_GRP_UNT 0xdeadbaac
#define MAX_USERS_IN_GROUP 1024
Typedefs
typedef struct GroupUnit GroupUnit_t
Functions
GroupHandel_t * GroupsHandel_Create ()
setup the process
char * DestoryAddres (GroupUnit_t *_value)
void GroupsHandel_Destroy (GroupHandel_t *_groupsHndl)
int GroupsHandel_NewGroup (GroupHandel_t *_groupsHndl, const char *_groupName, uint _socket, sockaddr_in_t *_addrs)
int GroupsHandel_JoinGroup (GroupHandel_t *_groupsHndl, const char *_groupName, uint _socket, sockaddr_in_t **_addrsOUT)
int GroupsHandel_IsGroupExist (GroupHandel_t *_groupsHndl, const char *_groupName)
sockaddr_in_t * GroupsHandel_GetGroupAddres (GroupHandel_t *_groupsHndl, const char *_groupName)
char * GetGroupNameToStr (void *_value, void *_buffer, uint *_num)
int GroupsHandel_GetGroupsName (GroupHandel_t *_groupsHndl, char *_groupsNames_out, size_t _bufferSize, size_t *_groupsLength_out)
Macro Definition Documentation
#define MAGIC_NUMBER_GRP_HNDL 0xdeadface
Definition at line 14 of file groupsHandle.c.
Referenced by GroupsHandel_Create(), and GroupsHandel_GetGroupsName().
#define MAGIC_NUMBER_GRP_UNT 0xdeadbaac
Definition at line 15 of file groupsHandle.c.
Referenced by GroupsHandel_GetGroupsName().
#define MAX_USERS_IN_GROUP 1024
Definition at line 17 of file groupsHandle.c.
Typedef Documentation
typedef struct GroupUnit GroupUnit_t
Function Documentation
char* DestoryAddres (GroupUnit_t * _value)
Definition at line 72 of file groupsHandle.c.
References GroupUnit::m_groupAddrs.
char* GetGroupNameToStr (void * _value, void * _buffer, uint * _num)
Definition at line 194 of file groupsHandle.c.
Referenced by GroupsHandel_GetGroupsName().
GroupHandel_t* GroupsHandel_Create ()
setup the process
Returns
a pointer to the struct
Definition at line 51 of file groupsHandle.c.
References ds_hashmap_create(), GroupHandel::m_groupContiner, GroupHandel::m_magicNumber, and MAGIC_NUMBER_GRP_HNDL.
Referenced by WhatDownBackEndApp_Create().
void GroupsHandel_Destroy (GroupHandel_t * _groupsHndl)
Definition at line 78 of file groupsHandle.c.
References ds_hashmap_free(), IsStructValid(), GroupHandel::m_groupContiner, and GroupHandel::m_magicNumber.
Referenced by WhatDownBackEndApp_Create(), and WhatDownBackEndApp_Destroy().
sockaddr_in_t* GroupsHandel_GetGroupAddres (GroupHandel_t * _groupsHndl, const char * _groupName)
Definition at line 175 of file groupsHandle.c.
References FALSE, IsStructValid(), and GroupUnit::m_groupAddrs.
int GroupsHandel_GetGroupsName (GroupHandel_t * _groupsHndl, char * _groupsNames_out, size_t _bufferSize, size_t * _groupsLength_out)
Definition at line 201 of file groupsHandle.c.
References CreateValue(), ds_hashmap_foreach_valueAction(), ds_hashmap_get_str(), FALSE, GEN_ERROR, GetGroupNameToStr(), IsStructValid(), GroupUnit::m_groupAddrs, GroupHandel::m_groupContiner, GroupUnit::m_groupName, GroupHandel::m_magicNumber, GroupUnit::m_magicNumber, GroupUnit::m_userInGroupNum, GroupUnit::m_usersSockets, MAGIC_NUMBER_GRP_HNDL, MAGIC_NUMBER_GRP_UNT, and TRUE.
Referenced by LogicBE_ErrorFunc().
int GroupsHandel_IsGroupExist (GroupHandel_t * _groupsHndl, const char * _groupName)
Definition at line 159 of file groupsHandle.c.
References ds_hashmap_get_str(), FALSE, IsStructValid(), GroupHandel::m_groupContiner, and TRUE.
Referenced by GroupsHandel_NewGroup(), and LogicBE_ErrorFunc().
int GroupsHandel_JoinGroup (GroupHandel_t * _groupsHndl, const char * _groupName, uint _socket, sockaddr_in_t ** _addrsOUT)
Definition at line 126 of file groupsHandle.c.
References FALSE, IsStructValid(), GroupUnit::m_groupAddrs, and TRUE.
Referenced by LogicBE_ErrorFunc().
int GroupsHandel_NewGroup (GroupHandel_t * _groupsHndl, const char * _groupName, uint _socket, sockaddr_in_t * _addrs)
Definition at line 99 of file groupsHandle.c.
References CreateValue(), ds_hashmap_put_str(), FALSE, GroupsHandel_IsGroupExist(), IsStructValid(), GroupHandel::m_groupContiner, and TRUE.
Referenced by LogicBE_ErrorFunc().