backEnd_src/groupsHandle.h File Reference
handle the groups of chats information. the groups that exist, their address, their members and so on.
#include `defines.h`
*
Typedefs
typedef struct sockaddr_in sockaddr_in_t
typedef struct GroupHandel GroupHandel_t
Functions
GroupHandel_t * GroupsHandel_Create ()
void GroupsHandel_Destroy (GroupHandel_t *_groupsHndl)
bool GroupsHandel_NewGroup (GroupHandel_t *_groupsHndl, const char *_groupName, uint _socket, sockaddr_in_t *_addrs)
bool GroupsHandel_JoinGroup (GroupHandel_t *_groupsHndl, const char *_groupName, uint _socket, sockaddr_in_t **_addrsOUT)
bool GroupsHandel_LeaveGroup (GroupHandel_t *_groupsHndl, const char *_groupName, uint _socket)
bool GroupsHandel_IsGroupExist (GroupHandel_t *_groupsHndl, const char *_groupName)
sockaddr_in_t * GroupsHandel_GetGroupAddres (GroupHandel_t *_groupsHndl, const char *_groupName)
int GroupsHandel_GetGroupsName (GroupHandel_t *_groupsHndl, char *_groupsNames_out, size_t _bufferSize, size_t *_groupsLength_out)
Detailed Description
handle the groups of chats information. the groups that exist, their address, their members and so on.
Date
Jul 16, 2017
Author
Yuval Hamberg
Typedef Documentation
typedef struct GroupHandel GroupHandel_t
Definition at line 21 of file groupsHandle.h.
typedef struct sockaddr_in sockaddr_in_t
Definition at line 16 of file groupsHandle.h.
Function Documentation
GroupHandel_t* GroupsHandel_Create ()
Definition at line 51 of file groupsHandle.c.
References ds_hashmap_create(), GroupHandel::m_groupContiner, GroupHandel::m_magicNumber, and MAGIC_NUMBER_GRP_HNDL.
Referenced by WhatDownBackEndApp_Create().
void GroupsHandel_Destroy (GroupHandel_t * _groupsHndl)
Definition at line 78 of file groupsHandle.c.
References ds_hashmap_free(), IsStructValid(), GroupHandel::m_groupContiner, and GroupHandel::m_magicNumber.
Referenced by WhatDownBackEndApp_Create(), and WhatDownBackEndApp_Destroy().
sockaddr_in_t* GroupsHandel_GetGroupAddres (GroupHandel_t * _groupsHndl, const char * _groupName)
Definition at line 175 of file groupsHandle.c.
References FALSE, IsStructValid(), and GroupUnit::m_groupAddrs.
int GroupsHandel_GetGroupsName (GroupHandel_t * _groupsHndl, char * _groupsNames_out, size_t _bufferSize, size_t * _groupsLength_out)
Definition at line 201 of file groupsHandle.c.
References CreateValue(), ds_hashmap_foreach_valueAction(), ds_hashmap_get_str(), FALSE, GEN_ERROR, GetGroupNameToStr(), IsStructValid(), GroupUnit::m_groupAddrs, GroupHandel::m_groupContiner, GroupUnit::m_groupName, GroupHandel::m_magicNumber, GroupUnit::m_magicNumber, GroupUnit::m_userInGroupNum, GroupUnit::m_usersSockets, MAGIC_NUMBER_GRP_HNDL, MAGIC_NUMBER_GRP_UNT, and TRUE.
Referenced by LogicBE_ErrorFunc().
bool GroupsHandel_IsGroupExist (GroupHandel_t * _groupsHndl, const char * _groupName)
Definition at line 159 of file groupsHandle.c.
References ds_hashmap_get_str(), FALSE, IsStructValid(), GroupHandel::m_groupContiner, and TRUE.
Referenced by GroupsHandel_NewGroup(), and LogicBE_ErrorFunc().
bool GroupsHandel_JoinGroup (GroupHandel_t * _groupsHndl, const char * _groupName, uint _socket, sockaddr_in_t ** _addrsOUT)
Definition at line 126 of file groupsHandle.c.
References FALSE, IsStructValid(), GroupUnit::m_groupAddrs, and TRUE.
Referenced by LogicBE_ErrorFunc().
bool GroupsHandel_LeaveGroup (GroupHandel_t * _groupsHndl, const char * _groupName, uint _socket)
bool GroupsHandel_NewGroup (GroupHandel_t * _groupsHndl, const char * _groupName, uint _socket, sockaddr_in_t * _addrs)
Definition at line 99 of file groupsHandle.c.
References CreateValue(), ds_hashmap_put_str(), FALSE, GroupsHandel_IsGroupExist(), IsStructValid(), GroupHandel::m_groupContiner, and TRUE.
Referenced by LogicBE_ErrorFunc().