ds/hashmap.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include `hashmap.h`
*
Functions
struct DSHashMap * ds_hashmap_create ()
void ds_hashmap_free (struct DSHashMap *hash, bool free_data, bool free_string_keys)
void ds_puts (struct DSHashMap *hash, char *key, void *data)
void ds_hashmap_put_str (struct DSHashMap *hash, char *key, void *data)
void ds_puti (struct DSHashMap *hash, int32_t key, void *data)
void ds_hashmap_put_int (struct DSHashMap *hash, int32_t key, void *data)
void ds_hashmap_remove_str (struct DSHashMap *hash, char *key, bool free_data, bool free_string_keys)
void ds_hashmap_remove_int (struct DSHashMap *hash, int32_t key, bool free_data)
void * ds_hashmap_get_key (struct DSHashKey *key)
void * ds_gets (struct DSHashMap *hash, char *key)
void * ds_hashmap_get_str (struct DSHashMap *hash, char *key)
void * ds_geti (struct DSHashMap *hash, int32_t key)
void * ds_hashmap_get_int (struct DSHashMap *hash, int32_t key)
void ds_hashmap_print_keys (struct DSHashMap *hash)
void ds_hashmap_print_keyvals (struct DSHashMap *hash, char *(tostring)(void *))
void ds_hashmap_foreach_value (struct DSHashMap *hash, char *(tostring)(void *))
int ds_hashmap_foreach_valueAction (struct DSHashMap *hash, void *_contex, char *(valueActFunc)(void *, void *_buffer, uint *_num))
void ds_hashmap_sort_keys (struct DSHashMap *hash)
void ds_hashmap_sort_by (struct DSHashMap *hash, int32_t(compare)(void *, void *))
Function Documentation
void* ds_geti (struct DSHashMap * hash, int32_t key)
Definition at line 250 of file hashmap.c.
References ds_hashmap_get_int().
Referenced by ds_hashmap_foreach_value(), ds_hashmap_get_key(), and ds_hashmap_print_keyvals().
void* ds_gets (struct DSHashMap * hash, char * key)
Definition at line 238 of file hashmap.c.
References ds_hashmap_get_str().
Referenced by ds_hashmap_foreach_value(), ds_hashmap_foreach_valueAction(), ds_hashmap_get_key(), and ds_hashmap_print_keyvals().
struct DSHashMap* ds_hashmap_create ()
Initializes a HashMap.
Definition at line 38 of file hashmap.c.
References DSHashMap::buckets, ds_vector_create(), and DSHashMap::keys.
Referenced by GroupsHandel_Create(), and UsersHandle_Create().
void ds_hashmap_foreach_value (struct DSHashMap * hash, char * tostring)(void *)
Definition at line 341 of file hashmap.c.
References ds_geti(), ds_gets(), DS_HASHMAP_KEY_INT, DS_HASHMAP_KEY_STRING, ds_vector_get(), DSHashKey::i, DSHashKey::key, DSHashMap::keys, DSHashKey::keytype, DSHashKey::s, and DSVector::size.
int ds_hashmap_foreach_valueAction (struct DSHashMap * hash, void * _contex, char * valueActFunc)(void *, void *_buffer, uint *_num)
Definition at line 362 of file hashmap.c.
References ds_gets(), DS_HASHMAP_KEY_INT, DS_HASHMAP_KEY_STRING, ds_vector_get(), DSHashKey::i, DSHashKey::key, DSHashMap::keys, DSHashKey::keytype, DSHashKey::s, and DSVector::size.
Referenced by GroupsHandel_GetGroupsName().
void ds_hashmap_free (struct DSHashMap * hash, bool free_data, bool free_string_keys)
Frees all memory associated with the hash map. If 'free_data' is true, user data will be freed too. If 'free_string_keys' is true, then string keys will be freed too.
Definition at line 57 of file hashmap.c.
References DSHashMap::buckets, DSHashItem::data, DS_HASHMAP_KEY_STRING, ds_vector_free_no_data(), DSHashItem::key, DSHashKey::key, DSHashMap::keys, DSHashKey::keytype, DSHashItem::next, and DSHashKey::s.
Referenced by GroupsHandel_Destroy(), and UsersHandle_Destroy().
void* ds_hashmap_get_int (struct DSHashMap * hash, int32_t key)
Gets an element with integer key from hash map.
Definition at line 256 of file hashmap.c.
References DSHashMap::buckets, DSHashItem::data, DS_HASHMAP_KEY_INT, DS_HASHMAP_KEY_STRING, DSHashItem::key, and DSHashItem::next.
Referenced by ds_geti().
void* ds_hashmap_get_key (struct DSHashKey * key)
Gets an element if you have a DSHashKey struct.
Definition at line 224 of file hashmap.c.
References ds_geti(), ds_gets(), DS_HASHMAP_KEY_INT, DS_HASHMAP_KEY_STRING, DSHashKey::hash, DSHashKey::i, DSHashKey::key, DSHashKey::keytype, and DSHashKey::s.
void* ds_hashmap_get_str (struct DSHashMap * hash, char * key)
Gets an element with string key from hash map.
Definition at line 244 of file hashmap.c.
References DS_HASHMAP_KEY_STRING.
Referenced by ds_gets(), GroupsHandel_GetGroupsName(), GroupsHandel_IsGroupExist(), UsersHandle_IsUserExist(), and UsersHandle_IsUserPasswordMatch().
void ds_hashmap_print_keys (struct DSHashMap * hash)
Prints a list of key names/numbers for debugging purposes.
Definition at line 296 of file hashmap.c.
References DS_HASHMAP_KEY_INT, DS_HASHMAP_KEY_STRING, ds_vector_get(), DSHashKey::i, DSHashKey::key, DSHashMap::keys, DSHashKey::keytype, DSHashKey::s, and DSVector::size.
void ds_hashmap_print_keyvals (struct DSHashMap * hash, char * tostring)(void *)
Prints a list of key,value pairs for debugging purposes. This needs a function that turns values into strings.
Definition at line 317 of file hashmap.c.
References ds_geti(), ds_gets(), DS_HASHMAP_KEY_INT, DS_HASHMAP_KEY_STRING, ds_vector_get(), DSHashKey::i, DSHashKey::key, DSHashMap::keys, DSHashKey::keytype, DSHashKey::s, and DSVector::size.
void ds_hashmap_put_int (struct DSHashMap * hash, int32_t key, void * data)
Adds an element with integer key to hash map.
Definition at line 103 of file hashmap.c.
References DSHashMap::buckets, DSHashItem::data, DS_HASHMAP_KEY_INT, DS_HASHMAP_KEY_STRING, ds_vector_append(), DSHashKey::hash, DSHashKey::i, DSHashItem::key, DSHashKey::key, DSHashMap::keys, DSHashKey::keytype, DSHashItem::next, and DSHashKey::s.
Referenced by ds_puti().
void ds_hashmap_put_str (struct DSHashMap * hash, char * key, void * data)
Adds an element with string key to hash map.
Definition at line 91 of file hashmap.c.
References DS_HASHMAP_KEY_STRING.
Referenced by ds_puts(), GroupsHandel_NewGroup(), and UsersHandle_AddNewUser().
void ds_hashmap_remove_int (struct DSHashMap * hash, int32_t key, bool free_data)
Similarly as 'ds_hashmap_remove_str' but with an integer as a key. Since an integer is a key, there is never a need to free a string key.
Definition at line 171 of file hashmap.c.
References DSHashMap::buckets, DSHashItem::data, DS_HASHMAP_KEY_INT, DS_HASHMAP_KEY_STRING, ds_vector_get(), ds_vector_remove(), DSHashItem::key, DSHashKey::key, DSHashMap::keys, DSHashItem::next, DSHashKey::s, and DSVector::size.
void ds_hashmap_remove_str (struct DSHashMap * hash, char * key, bool free_data, bool free_string_keys)
Removes an element using a string key. If 'free_data' is true, then all user data will be freed. If 'free_string_keys' is true, then all string will be freed.
Definition at line 163 of file hashmap.c.
References DS_HASHMAP_KEY_STRING.
void ds_hashmap_sort_by (struct DSHashMap * hash, int32_t(compare)(void *, void *))
Sorts the keys using the provided compare function. The compare function is defined as follows: compare(k1, k2) < 0 when k1 < k2 compare(k1, k2) = 0 when k1 = k2 compare(k1, k2) > 0 when k1 > k2
NOTE: The comparison doesn't have to be on the keys directly. One could use ds_get and compare those values.
Definition at line 391 of file hashmap.c.
References DS_HASHMAP_KEY_INT, DS_HASHMAP_KEY_STRING, ds_vector_sort(), DSHashKey::i, DSHashKey::key, DSHashMap::keys, DSHashKey::keytype, and DSHashKey::s.
Referenced by ds_hashmap_sort_keys().
void ds_hashmap_sort_keys (struct DSHashMap * hash)
Sorts the keys in alphanumeric order.
Definition at line 385 of file hashmap.c.
References ds_hashmap_sort_by().
void ds_puti (struct DSHashMap * hash, int32_t key, void * data)
Definition at line 97 of file hashmap.c.
References ds_hashmap_put_int().
void ds_puts (struct DSHashMap * hash, char * key, void * data)
Some shortcut functions: ds_puts -> ds_hashmap_put_str ds_puti -> ds_hashmap_put_int ds_gets -> ds_hashmap_get_str ds_geti -> ds_hashmap_get_int
Definition at line 85 of file hashmap.c.
References ds_hashmap_put_str().