backEnd_src/ipHandle.h File Reference
A handle of communication address. IP and port, holds a struct sockaddr_in of unused ones. FIFO implamentaion.
#include `defines.h`
*
Typedefs
typedef struct sockaddr_in sockaddr_in_t
typedef struct IP_Handle IP_Handle_t
Functions
IP_Handle_t * IP_Handle_Create (const char *_firestIP, uint _maxNumOfIPs, uint _portNum)
void IP_Handle_Destory (IP_Handle_t *_ipHndl)
sockaddr_in_t * IP_Handle_GetFreeIP (IP_Handle_t *_ipHndl)
bool IP_Handle_Release (IP_Handle_t *_ipHndl, sockaddr_in_t *_addressToRelease)
Detailed Description
A handle of communication address. IP and port, holds a struct sockaddr_in of unused ones. FIFO implamentaion.
Date
Jul 16, 2017
Author
Yuval Hamberg
add comments to API
Typedef Documentation
typedef struct IP_Handle IP_Handle_t
Definition at line 23 of file ipHandle.h.
typedef struct sockaddr_in sockaddr_in_t
Definition at line 18 of file ipHandle.h.
Function Documentation
IP_Handle_t* IP_Handle_Create (const char * _firestIP, uint _maxNumOfIPs, uint _portNum)
Definition at line 37 of file ipHandle.c.
References ds_queue_create(), IP_Handle::m_ipContiner, IP_Handle::m_magicNumber, and MAGIC_NUMBER_ALIVE_IP_HANDLE.
Referenced by WhatDownBackEndApp_Create().
void IP_Handle_Destory (IP_Handle_t * _ipHndl)
Definition at line 66 of file ipHandle.c.
References ds_queue_free(), ds_queue_get(), ds_queue_length(), IsStructValid(), IP_Handle::m_ipContiner, and IP_Handle::m_magicNumber.
Referenced by WhatDownBackEndApp_Create(), and WhatDownBackEndApp_Destroy().
sockaddr_in_t* IP_Handle_GetFreeIP (IP_Handle_t * _ipHndl)
Definition at line 91 of file ipHandle.c.
References ds_queue_get(), ds_queue_length(), IsStructValid(), and IP_Handle::m_ipContiner.
Referenced by LogicBE_ErrorFunc().
bool IP_Handle_Release (IP_Handle_t * _ipHndl, sockaddr_in_t * _addressToRelease)
Definition at line 107 of file ipHandle.c.
References ds_queue_capacity(), ds_queue_length(), ds_queue_put(), FALSE, IsStructValid(), IP_Handle::m_ipContiner, IP_Handle::m_magicNumber, MAGIC_NUMBER_ALIVE_IP_HANDLE, and TRUE.