backEnd_src/ipHandle.c File Reference
#include <netinet/in.h>
*
#include <sys/socket.h>
*
#include <arpa/inet.h>
*
#include `ipHandle.h`
*
#include `queue.h`
*
Data Structures
struct IP_Handle
Macros
#define MAGIC_NUMBER_ALIVE_IP_HANDLE 0xeeccface
Functions
IP_Handle_t * IP_Handle_Create (const char *_firestIP, uint _maxNumOfIPs, uint _portNum)
void IP_Handle_Destory (IP_Handle_t *_ipHndl)
sockaddr_in_t * IP_Handle_GetFreeIP (IP_Handle_t *_ipHndl)
asks for an address to use. no one also would use it until the caller returns it.
bool IP_Handle_Release (IP_Handle_t *_ipHndl, sockaddr_in_t *_addressToRelease)
Macro Definition Documentation
#define MAGIC_NUMBER_ALIVE_IP_HANDLE 0xeeccface
Definition at line 17 of file ipHandle.c.
Referenced by IP_Handle_Create(), and IP_Handle_Release().
Function Documentation
IP_Handle_t* IP_Handle_Create (const char * _firestIP, uint _maxNumOfIPs, uint _portNum)
Definition at line 37 of file ipHandle.c.
References ds_queue_create(), IP_Handle::m_ipContiner, IP_Handle::m_magicNumber, and MAGIC_NUMBER_ALIVE_IP_HANDLE.
Referenced by WhatDownBackEndApp_Create().
void IP_Handle_Destory (IP_Handle_t * _ipHndl)
Definition at line 66 of file ipHandle.c.
References ds_queue_free(), ds_queue_get(), ds_queue_length(), IsStructValid(), IP_Handle::m_ipContiner, and IP_Handle::m_magicNumber.
Referenced by WhatDownBackEndApp_Create(), and WhatDownBackEndApp_Destroy().
sockaddr_in_t* IP_Handle_GetFreeIP (IP_Handle_t * _ipHndl)
asks for an address to use. no one also would use it until the caller returns it.
Parameters
_ipHndl the pointer to the struct
Returns
pointer to the address struct used in network module. NULL if errors.
Definition at line 91 of file ipHandle.c.
References ds_queue_get(), ds_queue_length(), IsStructValid(), and IP_Handle::m_ipContiner.
Referenced by LogicBE_ErrorFunc().
bool IP_Handle_Release (IP_Handle_t * _ipHndl, sockaddr_in_t * _addressToRelease)
Definition at line 107 of file ipHandle.c.
References ds_queue_capacity(), ds_queue_length(), ds_queue_put(), FALSE, IsStructValid(), IP_Handle::m_ipContiner, IP_Handle::m_magicNumber, MAGIC_NUMBER_ALIVE_IP_HANDLE, and TRUE.