frontEnd_src/logic_FE.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <sys/socket.h>
*
#include <netinet/in.h>
*
#include <arpa/inet.h>
*
#include `logicFE.h`
*
#include `Protocol.h`
*
Data Structures
struct Logic_FE
Macros
#define NDBUG /* remove for debug */
#define MAGIC_NUMBER_ALIVE_LOGIC_FE 0xfacecdcd
#define WINDOW_HIGHT_WRITER 10
#define WINDOW_HIGHT_READER 30
#define WINDOW_WIDTH 100
#define WINDOW_X_POS 100
#define WINDOW_Y_POS_WRITER 600
#define WINDOW_Y_POS_READER 0
Functions
Logic_FE_t * LogicFE_Create (TCP_C_t *_netClient)
create and setup
int LogicFE_Signup (Logic_FE_t *_logic, const char *_username, const char *_password)
Handle the send and receive of Signup request and answer to the server.
int LogicFE_Login (Logic_FE_t *_logic, const char *_username, const char *_password)
Handle the send and receive of login request and answer to the server.
int LogicFE_CreateGroup (Logic_FE_t *_logic, const char *_groupName)
Handle the send and receive of login request and answer to the server.
int LogicFE_JoinGroup (Logic_FE_t *_logic, const char *_groupName)
Handle the send and receive of join an existing group request and answer to the server.
int LogicFE_GetAllGroupsName (Logic_FE_t *_logic, char *_groupsName_out, uint *_numOfGroups_out, uint _bufferSize)
Handle the send and receive of join an existing group request and answer to the server.
Macro Definition Documentation
#define MAGIC_NUMBER_ALIVE_LOGIC_FE 0xfacecdcd
Definition at line 22 of file logic_FE.c.
Referenced by LogicFE_Create(), and LogicFE_GetAllGroupsName().
#define NDBUG /* remove for debug */
Definition at line 21 of file logic_FE.c.
#define WINDOW_HIGHT_READER 30
#define WINDOW_HIGHT_WRITER 10
#define WINDOW_WIDTH 100
#define WINDOW_X_POS 100
#define WINDOW_Y_POS_READER 0
#define WINDOW_Y_POS_WRITER 600
Function Documentation
Logic_FE_t* LogicFE_Create (TCP_C_t * netClient)
create and setup
Parameters
netClient a pointer to the TCP net for client connection
Returns
the pointer to the struct
Definition at line 52 of file logic_FE.c.
References Logic_FE::m_magicNumer, Logic_FE::m_netClient, Logic_FE::m_recivebuf, Logic_FE::m_userName, and MAGIC_NUMBER_ALIVE_LOGIC_FE.
Referenced by WhatDownClientApp_Create().
int LogicFE_CreateGroup (Logic_FE_t * _logic, const char * _groupName)
Handle the send and receive of login request and answer to the server.
Parameters
_logic the pointer to the module struct.
_groupName char* the group name to be created.
Returns
TRUE for success. FALSE for fail
Definition at line 163 of file logic_FE.c.
References BackEnd_SUCCESS, IsStructValid(), ClientReceiveMessage::m_groupAdrres, Logic_FE::m_netClient, Logic_FE::m_recivebuf, Logic_FE::m_userName, MAX_MESSAGE_LENGTH, and Protocol_EncodeNewGroup().
Referenced by CreateNewGroupFunction().
int LogicFE_GetAllGroupsName (Logic_FE_t * _logic, char * _GroupsName_out, uint * _numOfGroups_out, uint _bufferSize)
Handle the send and receive of join an existing group request and answer to the server.
Parameters
_logic the pointer to the module struct.
_GroupsName_out a string with all the groups name. divided by delimiter
_numOfGroups_out how many group have been read.
_bufferSize the max size of buffer to be copied to.
Returns
Definition at line 252 of file logic_FE.c.
References BackEnd_SUCCESS, BackEnd_SYSTEM_FAIL, FALSE, IsStructValid(), ClientReceiveMessage::m_GroupName, Logic_FE::m_magicNumer, ClientReceiveMessage::m_messageType, Logic_FE::m_netClient, ClientReceiveMessage::m_numberOfGroups, Logic_FE::m_recivebuf, ClientReceiveMessage::m_status, MAGIC_NUMBER_ALIVE_LOGIC_FE, MAX_MESSAGE_LENGTH, Protocol_DecodeClient(), Protocol_EncodeGetAllGroups(), TCP_ClientRecive(), TCP_ClientSend(), and TRUE.
Referenced by GetAllGruopFunction().
int LogicFE_JoinGroup (Logic_FE_t * _logic, const char * _groupName)
Handle the send and receive of join an existing group request and answer to the server.
Parameters
_logic the pointer to the module struct.
_groupName char* the group name to be created.
Returns
TRUE for success. FALSE for fail
Definition at line 207 of file logic_FE.c.
References BackEnd_SUCCESS, IsStructValid(), ClientReceiveMessage::m_groupAdrres, Logic_FE::m_netClient, Logic_FE::m_recivebuf, Logic_FE::m_userName, MAX_MESSAGE_LENGTH, and Protocol_EncodeJoinGroup().
Referenced by JoinGruopFunction().
int LogicFE_Login (Logic_FE_t * _logic, const char * _username, const char * _password)
Handle the send and receive of login request and answer to the server.
Parameters
_logic the pointer to the module struct.
_username char* msg
_password char* msg
Returns
TRUE for success. FALSE for fail
Definition at line 122 of file logic_FE.c.
References BackEnd_SUCCESS, GEN_ERROR, IsStructValid(), Logic_FE::m_netClient, Logic_FE::m_recivebuf, Logic_FE::m_userName, MAX_MESSAGE_LENGTH, and Protocol_EncodeLogIn().
Referenced by LoginFunction().
int LogicFE_Signup (Logic_FE_t * _logic, const char * _username, const char * _password)
Handle the send and receive of Signup request and answer to the server.
Parameters
_logic the pointer to the module struct.
_username char* msg
_password char* msg
Returns
TRUE for success. FALSE for fail
Definition at line 82 of file logic_FE.c.
References BackEnd_SUCCESS, GEN_ERROR, IsStructValid(), Logic_FE::m_netClient, Logic_FE::m_recivebuf, Logic_FE::m_userName, MAX_MESSAGE_LENGTH, and Protocol_EncodeSignUp().
Referenced by SignupFunction().