backEnd_src/logic_backEnd.c File Reference
#include <string.h>
*
#include <err.h>
*
#include `logic_backEnd.h`
*
#include `Protocol.h`
*
#include `usersHandle.h`
*
#include `ipHandle.h`
*
#include `groupsHandle.h`
*
Data Structures
struct Logic_BE
Macros
#define MAGIC_NUMBER_BE_LOGIC 0xfacebaad
#define MINIMAL_USER_PASSWORD 3
Functions
Logic_BE_t * LogicBE_Create (void *_usersHandel, void *_groupHandle, void *_IP_handle)
create and setup for the process
int LogicBE_SetServerPTR (Logic_BE_t *_logicBE, TCP_S_t *_server)
add to the logic the pointer to the TCP server. as both modules in to be setup at the same time, the pointer is added just after create.
void LogicBE_Destroy (Logic_BE_t *_logicBE)
cleans up after the processing
int LogicBE_ReciveDataFunc (void *_data, size_t _sizeData, uint _socketNum, void *_contex)
call back function when TCP server get a msg.
int LogicBE_NewClientFunc (uint _socketNum, void *_contex)
call bacl function when TCP server get a new client connected to .
int LogicBE_ClientDissconnectedFunc (uint _socketNum, void *_contex)
call bacl function when TCP server get a client disconnect to .
int LogicBE_ErrorFunc (int _status, uint _socketNum, void *_contex)
call bacl function when TCP server get an error.
Macro Definition Documentation
#define MAGIC_NUMBER_BE_LOGIC 0xfacebaad
Definition at line 18 of file logic_backEnd.c.
Referenced by LogicBE_Create(), and LogicBE_ErrorFunc().
#define MINIMAL_USER_PASSWORD 3
Definition at line 20 of file logic_backEnd.c.
Referenced by LogicBE_ErrorFunc().
Function Documentation
int LogicBE_ClientDissconnectedFunc (uint _socketNum, void * _contex)
call bacl function when TCP server get a client disconnect to .
Parameters
_socketNum file descriptor of the incoming data originated from.
_contex was given to the TCP server at create. usually the pointer to Logic_BE.
Returns
TRUE for success and FALSE for errors
Definition at line 175 of file logic_backEnd.c.
Referenced by WhatDownBackEndApp_Create().
Logic_BE_t* LogicBE_Create (void * _usersHandel, void * _groupHandle, void * _IP_handle)
create and setup for the process
Parameters
_usersHandel a pointer the the module the deals with Users.
_groupHandle a pointer the the module the deals with chat groups.
_IP_handle a pointer the the module the deals with allocatin IP address.
Returns
a pointer to the struct
Definition at line 53 of file logic_backEnd.c.
References Logic_BE::m_decodedMsg, Logic_BE::m_groupHandle, Logic_BE::m_IP_handle, Logic_BE::m_magicNumber, Logic_BE::m_usersHandel, and MAGIC_NUMBER_BE_LOGIC.
Referenced by WhatDownBackEndApp_Create().
void LogicBE_Destroy (Logic_BE_t * _logic)
cleans up after the processing
Parameters
_logic a pointer to the TCP server
Definition at line 95 of file logic_backEnd.c.
References IsStructValid(), Logic_BE::m_decodedMsg, Logic_BE::m_magicNumber, Logic_BE::m_net, and TCP_DestroyServer().
Referenced by WhatDownBackEndApp_Create(), and WhatDownBackEndApp_Destroy().
int LogicBE_ErrorFunc (int _status, uint _socketNum, void * _contex)
call bacl function when TCP server get an error.
Parameters
_status represnt the error.
_socketNum file descriptor of the incoming data originated from.
_contex was given to the TCP server at create. usually the pointer to Logic_BE.
Returns
TRUE for success and FALSE for errors
Definition at line 183 of file logic_backEnd.c.
References BackEnd_GROUP_DO_NOT_EXIST, BackEnd_GROUP_NAME_INVALID, BackEnd_GROUP_NAME_TAKEN, BackEnd_NO_FREE_IP, BackEnd_PASSWORD_INVALID, BackEnd_SUCCESS, BackEnd_SYSTEM_FAIL, BackEnd_USER_NAME_INVALID, BackEnd_USER_NAME_TAKEN, BackEnd_USER_NOT_FOUND, DELIMITER, DELIMITER_LENGHT, FALSE, GroupsHandel_GetGroupsName(), GroupsHandel_IsGroupExist(), GroupsHandel_JoinGroup(), GroupsHandel_NewGroup(), IP_Handle_GetFreeIP(), IsStructValid(), Logic_BE::m_decodedMsg, Logic_BE::m_groupHandle, ServerReceiveMessage::m_groupName, Logic_BE::m_IP_handle, Logic_BE::m_magicNumber, ServerReceiveMessage::m_password, ServerReceiveMessage::m_userName, Logic_BE::m_usersHandel, MAGIC_NUMBER_BE_LOGIC, MAX_GROUP_NAME, MAX_MESSAGE_LENGTH, MAX_PASSWORD, MAX_USERNAME, MESSAGETYPE_CREATE_GROUP, MESSAGETYPE_DELETE_USER, MESSAGETYPE_GET_ALL_GROUPS, MESSAGETYPE_JOIN_GROUP, MESSAGETYPE_LEAVE_GROUP, MESSAGETYPE_LOGIN, MESSAGETYPE_LOGOUT, MESSAGETYPE_SIGNUP, MINIMAL_USER_PASSWORD, Protocol_EncodeGetAllGroups_Response(), Protocol_EncodeJoinGroup_Response(), Protocol_EncodeLogIn_Response(), Protocol_EncodeNewGroup_Response(), Protocol_EncodeSignUp_Response(), TCP_Send(), TRUE, UsersHandle_AddNewUser(), UsersHandle_IsUserExist(), and UsersHandle_IsUserPasswordMatch().
Referenced by WhatDownBackEndApp_Create().
int LogicBE_NewClientFunc (uint _socketNum, void * _contex)
call bacl function when TCP server get a new client connected to .
Parameters
_socketNum file descriptor of the incoming data originated from.
_contex was given to the TCP server at create. usually the pointer to Logic_BE.
Returns
TRUE for success and FALSE for errors
Definition at line 168 of file logic_backEnd.c.
Referenced by WhatDownBackEndApp_Create().
int LogicBE_ReciveDataFunc (void * _data, size_t _sizeData, uint _socketNum, void * _contex)
call back function when TCP server get a msg.
call back functions (from the TCP server)
Parameters
_data the information received
_sizeData the number of bytes received
_socketNum file descriptor of the incoming data originated from.
_contex was given to the TCP server at create. usually the pointer to Logic_BE.
Returns
TRUE for success and FALSE for errors
Definition at line 112 of file logic_backEnd.c.
References GEN_ERROR, IsStructValid(), Logic_BE::m_decodedMsg, ServerReceiveMessage::m_MessageType, MESSAGETYPE_CREATE_GROUP, MESSAGETYPE_DELETE_USER, MESSAGETYPE_GET_ALL_GROUPS, MESSAGETYPE_JOIN_GROUP, MESSAGETYPE_LEAVE_GROUP, MESSAGETYPE_LOGIN, MESSAGETYPE_LOGOUT, MESSAGETYPE_SIGNUP, Protocol_DecodeServer(), and TRUE.
Referenced by WhatDownBackEndApp_Create().
int LogicBE_SetServerPTR (Logic_BE_t * _logicBE, TCP_S_t * _server)
add to the logic the pointer to the TCP server. as both modules in to be setup at the same time, the pointer is added just after create.
Parameters
_logicBE the pointer to the struct
_server a pointer to the TCP server
Returns
TRUE for succses and FALSE if one of the parameters is wrong
Definition at line 83 of file logic_backEnd.c.
References FALSE, IsStructValid(), Logic_BE::m_net, and TRUE.
Referenced by WhatDownBackEndApp_Create().