chats/netUDP_MultiCast.c File Reference
#include `netUDP_MultiCast.h`
*
#include <sys/types.h>
*
#include <sys/socket.h>
*
#include <netinet/in.h>
*
#include <arpa/inet.h>
*
#include <time.h>
*
#include <string.h>
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include <unistd.h>
*
Data Structures
struct UDP_MultiCast
Macros
#define MAGIC_NUMBER_ALIVE_SENDER 0xfacefedc
#define MAGIC_NUMBER_ALIVE_RECV 0xfaceabcd
Functions
UDP_MultiCast_t * UDP_MultiCast_Sender_Create (const char *_ip, uint _port)
create and setup for sending udp multi cast messages
void UDP_MultiCast_Sender_Destroy (UDP_MultiCast_t *_net)
destroy and clean up
int UDP_MultiCast_Send (UDP_MultiCast_t *_net, void *_msg, uint _msgLength)
actually sending the caller message
UDP_MultiCast_t * UDP_MultiCast_Reciver_Create (const char *_ip, uint _port)
create and setup for receiving udp multi cast messages
void UDP_MultiCast_Reciver_Destroy (UDP_MultiCast_t *_netRecive)
destroy and clean up
int UDP_MultiCast_Recive (UDP_MultiCast_t *_netRecive, void *_buffer, size_t _bufferSize)
perform a read of the address given at create. if nothing to read, would go to block until there would.
Macro Definition Documentation
#define MAGIC_NUMBER_ALIVE_RECV 0xfaceabcd
Definition at line 23 of file netUDP_MultiCast.c.
Referenced by UDP_MultiCast_Recive(), UDP_MultiCast_Reciver_Create(), and UDP_MultiCast_Reciver_Destroy().
#define MAGIC_NUMBER_ALIVE_SENDER 0xfacefedc
Definition at line 22 of file netUDP_MultiCast.c.
Referenced by UDP_MultiCast_Send(), UDP_MultiCast_Sender_Create(), and UDP_MultiCast_Sender_Destroy().
Function Documentation
int UDP_MultiCast_Recive (UDP_MultiCast_t * _netRecive, void * _buffer, size_t _bufferSize)
perform a read of the address given at create. if nothing to read, would go to block until there would.
Parameters
_netRecive a pointer to the new struct
_buffer the read information would be writing to this buffer.
_bufferSize the length in bytes of the buffer. no overflow would ocuur.
Returns
the size in bytes read. negative values represent errors.
Definition at line 204 of file netUDP_MultiCast.c.
References GEN_ERROR, UDP_MultiCast::m_fd_socket, UDP_MultiCast::m_magicNumber, UDP_MultiCast::m_sockaddr, and MAGIC_NUMBER_ALIVE_RECV.
Referenced by main().
UDP_MultiCast_t* UDP_MultiCast_Reciver_Create (const char * _ip, uint _port)
create and setup for receiving udp multi cast messages
Parameters
_ip the address in a XXX.XXX.XXX.XXX fomat
_port port number to receive on
Returns
a pointer to the new struct
Definition at line 114 of file netUDP_MultiCast.c.
References UDP_MultiCast::m_fd_socket, UDP_MultiCast::m_magicNumber, UDP_MultiCast::m_sockaddr, MAGIC_NUMBER_ALIVE_RECV, and TRUE.
Referenced by main().
void UDP_MultiCast_Reciver_Destroy (UDP_MultiCast_t * _net)
destroy and clean up
Parameters
_net pointer to struct
Definition at line 188 of file netUDP_MultiCast.c.
References UDP_MultiCast::m_fd_socket, UDP_MultiCast::m_magicNumber, UDP_MultiCast::m_sockaddr, and MAGIC_NUMBER_ALIVE_RECV.
int UDP_MultiCast_Send (UDP_MultiCast_t * _net, void * _msg, uint _msgLength)
actually sending the caller message
Parameters
_net pointer to struct
_msg the message to send
_msgLength the length in bytes of the msg
Returns
the length of bytes send. negative values represent errors.
Definition at line 94 of file netUDP_MultiCast.c.
References GEN_ERROR, UDP_MultiCast::m_fd_socket, UDP_MultiCast::m_magicNumber, UDP_MultiCast::m_sockaddr, and MAGIC_NUMBER_ALIVE_SENDER.
Referenced by main().
UDP_MultiCast_t* UDP_MultiCast_Sender_Create (const char * _ip, uint _port)
create and setup for sending udp multi cast messages
Parameters
_ip the address in a XXX.XXX.XXX.XXX fomat
_port port number to communicate on
Returns
a pointer to the new struct
Definition at line 39 of file netUDP_MultiCast.c.
References UDP_MultiCast::m_fd_socket, UDP_MultiCast::m_magicNumber, UDP_MultiCast::m_sockaddr, and MAGIC_NUMBER_ALIVE_SENDER.
Referenced by main().
void UDP_MultiCast_Sender_Destroy (UDP_MultiCast_t * _net)
destroy and clean up
Parameters
_net pointer to struct
Definition at line 78 of file netUDP_MultiCast.c.
References UDP_MultiCast::m_fd_socket, UDP_MultiCast::m_magicNumber, UDP_MultiCast::m_sockaddr, and MAGIC_NUMBER_ALIVE_SENDER.