comm/Protocol.h File Reference
#include <stdlib.h>
*
#include <sys/types.h>
*
#include <netinet/in.h>
*
Data Structures
struct ServerReceiveMessage
struct ClientReceiveMessage
Macros
#define BUFFER_SIZE 1024
#define TLV_TYPE_LENGTH 1
#define TLV_LENGTH_LENGHT 5
#define HEADER_LENGTH 6
#define MAX_MESSAGE_LENGTH 1024
#define MAX_USERNAME 32
#define MAX_PASSWORD 32
#define MAX_GROUP_NAME 32
#define NAX_IP_LENGTH 16
#define ourInt 32
#define DELIMITER `@@@`
#define DELIMITER_LENGHT 3
Typedefs
typedef struct sockaddr_in sockaddr_in_t
typedef enum MessageType MessageType
typedef enum BackEndStatus BackEndStatus
typedef struct ServerReceiveMessage ServerReceiveMessage_t
typedef struct ClientReceiveMessage ClientReceiveMessage_t
Enumerations
enum MessageType {
*
MESSAGETYPE_RESPONS = 65,
MESSAGETYPE_SIGNUP,
MESSAGETYPE_LOGIN,
MESSAGETYPE_LOGOUT,
*
MESSAGETYPE_DELETE_USER,
MESSAGETYPE_JOIN_GROUP,
MESSAGETYPE_CREATE_GROUP,
MESSAGETYPE_LEAVE_GROUP,
*
MESSAGETYPE_GET_ALL_GROUPS
 }
enum BackEndStatus {
*
BackEnd_SUCCESS = 66,
BackEnd_SYSTEM_FAIL,
BackEnd_UNKNOWN_ERROR,
BackEnd_USER_NAME_TAKEN,
*
BackEnd_USER_NAME_INVALID,
BackEnd_USER_NOT_FOUND,
BackEnd_PASSWORD_INVALID,
BackEnd_GROUP_NAME_TAKEN,
*
BackEnd_GROUP_NAME_INVALID,
BackEnd_GROUP_DO_NOT_EXIST,
BackEnd_MORE_INFO_INCOMING,
BackEnd_NO_FREE_IP,
*
BackEnd_CLIENT_DISCONNECTED,
BackEnd_REQUST_UNKNOWN
 }
Functions
int Protocol_EncodeNewGroup (const char *_groupName, void *_buffer)
The function Encode Message to Protocol format.
int Protocol_EncodeGetAllGroups (void *_buffer)
The function Encode Message to Protocol format.
int Protocol_EncodeJoinGroup (const char *_groupNameToJoin, void *_buffer)
The function Encode Message to Protocol format.
int Protocol_EncodeLeaveGroup (const char *_groupNameToLeave, void *_buffer)
The function Encode Message to Protocol format.
int Protocol_EncodeLogIn (const char *_userName, const char *_password, void *_buffer)
The function Encode Message to Protocol format.
int Protocol_EncodeLogOut (void *_buffer)
The function Encode Message to Protocol format.
int Protocol_EncodeSignUp (const char *_newUserName, const char *_password, void *_buffer)
The function Encode Message to Protocol format.
int Protocol_EncodeDeleteUser (void *_buffer)
The function Encode Message to Protocol format.
int Protocol_DecodeServer (void *_dataToDecode, size_t _lenght, ServerReceiveMessage_t *_message)
The function Decode Message from Protocol format to ServerReceiveMessage_t form.
int Protocol_DecodeClient (void *_dataToDecode, size_t _lenght, ClientReceiveMessage_t *_message)
The function Decode Message from Protocol format to ClientReceiveMessage_t form.
int Protocol_EncodeSignUp_Response (BackEndStatus _responseStatus, void *_buffer)
encode the response from server-end to front-end of sign-up respond
int Protocol_EncodeDeleteUser_Response (BackEndStatus _responseStatus, void *_buffer)
encode the response from server-end to front-end of delete user respond
int Protocol_EncodeLogIn_Response (BackEndStatus _responseStatus, void *_buffer)
encode the response from server-end to front-end of log-in respond
int Protocol_EncodeLogOut_Response (BackEndStatus _responseStatus, void *_buffer)
encode the response from server-end to front-end of log-out respond
int Protocol_EncodeNewGroup_Response (BackEndStatus _responseStatus, sockaddr_in_t m_groupAdrres, void *_buffer)
encode the response from server-end to front-end of create new group respond
int Protocol_EncodeJoinGroup_Response (BackEndStatus _responseStatus, sockaddr_in_t m_groupAdrres, void *_buffer)
encode the response from server-end to front-end of join group respond
int Protocol_EncodeLeaveGroup_Response (BackEndStatus _responseStatus, void *_buffer)
encode the response from server-end to front-end of leave group respond
int Protocol_EncodeGetAllGroups_Response (BackEndStatus _responseStatus, const char *_groupsNames, size_t _numGroups, void *_buffer)
encode the response from server-end to front-end of show all group respond
Macro Definition Documentation
#define BUFFER_SIZE 1024
Definition at line 20 of file Protocol.h.
#define DELIMITER `@@@`
Definition at line 31 of file Protocol.h.
Referenced by LogicBE_ErrorFunc(), Protocol_DecodeClient(), Protocol_DecodeServer(), Protocol_EncodeGetAllGroups(), Protocol_EncodeGetAllGroups_Response(), Protocol_EncodeJoinGroup(), Protocol_EncodeJoinGroup_Response(), Protocol_EncodeLogIn(), Protocol_EncodeLogIn_Response(), Protocol_EncodeNewGroup(), Protocol_EncodeNewGroup_Response(), Protocol_EncodeSignUp(), and Protocol_EncodeSignUp_Response().
#define DELIMITER_LENGHT 3
Definition at line 32 of file Protocol.h.
Referenced by LogicBE_ErrorFunc(), Protocol_DecodeClient(), Protocol_DecodeServer(), and Protocol_EncodeGetAllGroups_Response().
#define HEADER_LENGTH 6
Definition at line 24 of file Protocol.h.
#define MAX_GROUP_NAME 32
Definition at line 28 of file Protocol.h.
#define MAX_MESSAGE_LENGTH 1024
Definition at line 25 of file Protocol.h.
Referenced by LogicBE_ErrorFunc(), LogicFE_CreateGroup(), LogicFE_GetAllGroupsName(), LogicFE_JoinGroup(), LogicFE_Login(), LogicFE_Signup(), main(), Protocol_DecodeClient(), Protocol_DecodeServer(), Protocol_EncodeGetAllGroups(), Protocol_EncodeGetAllGroups_Response(), Protocol_EncodeJoinGroup(), Protocol_EncodeJoinGroup_Response(), Protocol_EncodeLogIn(), Protocol_EncodeLogIn_Response(), Protocol_EncodeNewGroup(), Protocol_EncodeNewGroup_Response(), Protocol_EncodeSignUp(), and Protocol_EncodeSignUp_Response().
#define MAX_PASSWORD 32
Definition at line 27 of file Protocol.h.
Referenced by CreateValue(), LogicBE_ErrorFunc(), LoginFunction(), main(), and SignupFunction().
#define MAX_USERNAME 32
Definition at line 26 of file Protocol.h.
Referenced by CreateValue(), LogicBE_ErrorFunc(), LoginFunction(), main(), and SignupFunction().
#define NAX_IP_LENGTH 16
Definition at line 29 of file Protocol.h.
#define ourInt 32
Definition at line 30 of file Protocol.h.
#define TLV_LENGTH_LENGHT 5
Definition at line 23 of file Protocol.h.
#define TLV_TYPE_LENGTH 1
Definition at line 22 of file Protocol.h.
Referenced by TLV_decode().
Typedef Documentation
typedef enum BackEndStatus BackEndStatus
typedef struct ClientReceiveMessage ClientReceiveMessage_t
typedef enum MessageType MessageType
typedef struct ServerReceiveMessage ServerReceiveMessage_t
typedef struct sockaddr_in sockaddr_in_t
Definition at line 35 of file Protocol.h.
Enumeration Type Documentation
enum BackEndStatus
Enumerator
BackEnd_SUCCESS
BackEnd_SYSTEM_FAIL
BackEnd_UNKNOWN_ERROR
BackEnd_USER_NAME_TAKEN
BackEnd_USER_NAME_INVALID
BackEnd_USER_NOT_FOUND
BackEnd_PASSWORD_INVALID
BackEnd_GROUP_NAME_TAKEN
BackEnd_GROUP_NAME_INVALID
BackEnd_GROUP_DO_NOT_EXIST
BackEnd_MORE_INFO_INCOMING
BackEnd_NO_FREE_IP
BackEnd_CLIENT_DISCONNECTED
BackEnd_REQUST_UNKNOWN
Definition at line 61 of file Protocol.h.
enum MessageType
Enumerator
MESSAGETYPE_RESPONS
MESSAGETYPE_SIGNUP
MESSAGETYPE_LOGIN
MESSAGETYPE_LOGOUT
MESSAGETYPE_DELETE_USER
MESSAGETYPE_JOIN_GROUP
MESSAGETYPE_CREATE_GROUP
MESSAGETYPE_LEAVE_GROUP
MESSAGETYPE_GET_ALL_GROUPS
Definition at line 47 of file Protocol.h.
Function Documentation
int Protocol_DecodeClient (void * _dataToDecode, size_t _lenght, ClientReceiveMessage_t * _message)
The function Decode Message from Protocol format to ClientReceiveMessage_t form.
Parameters
void* _dataToDecode - pointer to data that need to decoded
size_t _length - Data length
ClientReceiveMessage_t* _message - Receive Message that the function fill
Returns
bool on success true 1, on fail false 0.
Definition at line 134 of file protocol.c.
References BackEnd_SUCCESS, DELIMITER, DELIMITER_LENGHT, FALSE, GEN_ERROR, ClientReceiveMessage::m_messageType, ClientReceiveMessage::m_status, MAX_MESSAGE_LENGTH, MESSAGETYPE_CREATE_GROUP, MESSAGETYPE_DELETE_USER, MESSAGETYPE_GET_ALL_GROUPS, MESSAGETYPE_JOIN_GROUP, MESSAGETYPE_LEAVE_GROUP, MESSAGETYPE_LOGIN, MESSAGETYPE_LOGOUT, MESSAGETYPE_RESPONS, MESSAGETYPE_SIGNUP, TLV_decode(), TLV_MORE_TLVS_TO_DECODE, TLV_SUCCESS, and TRUE.
Referenced by LogicFE_GetAllGroupsName(), and main().
int Protocol_DecodeServer (void * _dataToDecode, size_t _lenght, ServerReceiveMessage_t * _message)
The function Decode Message from Protocol format to ServerReceiveMessage_t form.
Parameters
void* _dataToDecode - pointer to data that need to decoded
size_t _length - Data length
ServerReceiveMessage_t* _message - Receive Message that the function fill
Returns
bool on success true 1, on fail false 0.
Definition at line 206 of file protocol.c.
References DELIMITER, DELIMITER_LENGHT, FALSE, GEN_ERROR, ServerReceiveMessage::m_groupName, ServerReceiveMessage::m_MessageType, ServerReceiveMessage::m_password, ServerReceiveMessage::m_userName, MAX_MESSAGE_LENGTH, MESSAGETYPE_CREATE_GROUP, MESSAGETYPE_DELETE_USER, MESSAGETYPE_GET_ALL_GROUPS, MESSAGETYPE_JOIN_GROUP, MESSAGETYPE_LEAVE_GROUP, MESSAGETYPE_LOGIN, MESSAGETYPE_LOGOUT, MESSAGETYPE_RESPONS, MESSAGETYPE_SIGNUP, TLV_decode(), TLV_MORE_TLVS_TO_DECODE, TLV_SUCCESS, and TRUE.
Referenced by LogicBE_ReciveDataFunc(), and main().
int Protocol_EncodeDeleteUser (void * _buffer)
The function Encode Message to Protocol format.
Parameters
void* _buffer - Buffer that in which the message will written
Returns
on success message length. on fail -1
int Protocol_EncodeDeleteUser_Response (BackEndStatus _responseStatus, void * _buffer)
encode the response from server-end to front-end of delete user respond
Parameters
_responseStatus ENUM status of back-end result
_buffer the buffer in which msg to be send
Returns
on success message length. on fail -1
int Protocol_EncodeGetAllGroups (void * _buffer)
The function Encode Message to Protocol format.
Parameters
void* _buffer - Buffer that in which the message will written
Returns
on success message length. on fail -1
Definition at line 364 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_GET_ALL_GROUPS, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicFE_GetAllGroupsName().
int Protocol_EncodeGetAllGroups_Response (BackEndStatus _responseStatus, const char * _groupsNames, size_t _numGroups, void * _buffer)
encode the response from server-end to front-end of show all group respond
Parameters
_responseStatus ENUM status of back-end response
_groupsNames a string of groups names devided by \0
_numGroups the numer of groups in _groupsNames
_buffer the buffer in which msg to be send
Returns
on success message length. on fail -1
Definition at line 387 of file protocol.c.
References DELIMITER, DELIMITER_LENGHT, FALSE, GEN_ERROR, ClientReceiveMessage::m_groupAdrres, ClientReceiveMessage::m_GroupName, ClientReceiveMessage::m_numberOfGroups, MAX_MESSAGE_LENGTH, MESSAGETYPE_GET_ALL_GROUPS, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, TLV_SUCCESS, and TRUE.
Referenced by LogicBE_ErrorFunc().
int Protocol_EncodeJoinGroup (const char * _groupNameToJoin, void * _buffer)
The function Encode Message to Protocol format.
Parameters
Char* _groupNameToJoin - group name to join
void* _buffer - Buffer that in which the message will written
Returns
on success message length. on fail -1
Definition at line 318 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_JOIN_GROUP, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicFE_JoinGroup().
int Protocol_EncodeJoinGroup_Response (BackEndStatus _responseStatus, sockaddr_in_t m_groupAdrres, void * _buffer)
encode the response from server-end to front-end of join group respond
Parameters
_responseStatus ENUM status of back-end result
m_groupAdrres a struct that continues ip and port
_buffer the buffer in which msg to be send
Returns
on success message length. on fail -1
Definition at line 341 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_JOIN_GROUP, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicBE_ErrorFunc().
int Protocol_EncodeLeaveGroup (const char * _groupNameToLeave, void * _buffer)
The function Encode Message to Protocol format.
Parameters
Char* _groupNameToLeave - group name to Leave
void* _buffer - Buffer that in which the message will written
Returns
on success message length. on fail -1
int Protocol_EncodeLeaveGroup_Response (BackEndStatus _responseStatus, void * _buffer)
encode the response from server-end to front-end of leave group respond
Parameters
_responseStatus ENUM status of back-end result
_buffer the buffer in which msg to be send
Returns
on success message length. on fail -1
int Protocol_EncodeLogIn (const char * _userName, const char * _password, void * _buffer)
The function Encode Message to Protocol format.
Parameters
Char* _userName - User Name
Char* _password - Password
void* _buffer - Buffer that in which the message will written
Returns
on success message length. on fail -1
Definition at line 88 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_LOGIN, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicFE_Login().
int Protocol_EncodeLogIn_Response (BackEndStatus _responseStatus, void * _buffer)
encode the response from server-end to front-end of log-in respond
Parameters
_responseStatus ENUM status of back-end result
_buffer the buffer in which msg to be send
Returns
on success message length. on fail -1
Definition at line 111 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_LOGIN, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicBE_ErrorFunc().
int Protocol_EncodeLogOut (void * _buffer)
The function Encode Message to Protocol format.
Parameters
void* _buffer - Buffer that in which the message will written
Returns
on success message length. on fail -1
int Protocol_EncodeLogOut_Response (BackEndStatus _responseStatus, void * _buffer)
encode the response from server-end to front-end of log-out respond
Parameters
_responseStatus ENUM status of back-end result
_buffer the buffer in which msg to be send
Returns
on success message length. on fail -1
int Protocol_EncodeNewGroup (const char * _groupName, void * _buffer)
The function Encode Message to Protocol format.
Parameters
Char* _groupName - group name
void* _buffer - Buffer that in which the message will written
Returns
on success message length. on fail -1
Definition at line 272 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_CREATE_GROUP, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicFE_CreateGroup().
int Protocol_EncodeNewGroup_Response (BackEndStatus _responseStatus, sockaddr_in_t m_groupAdrres, void * _buffer)
encode the response from server-end to front-end of create new group respond
Parameters
_responseStatus ENUM status of back-end result
m_groupAdrres a struct that continues ip and port
_buffer the buffer in which msg to be send
Returns
on success message length. on fail -1
Definition at line 295 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_CREATE_GROUP, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicBE_ErrorFunc().
int Protocol_EncodeSignUp (const char * _newUserName, const char * _password, void * _buffer)
The function Encode Message to Protocol format.
Parameters
Char* _newUserName - User Name
Char* _password - Password
void* _buffer - Buffer that in which the message will written
Returns
on success message length. on fail -1
Definition at line 41 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_SIGNUP, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicFE_Signup(), and main().
int Protocol_EncodeSignUp_Response (BackEndStatus _responseStatus, void * _buffer)
encode the response from server-end to front-end of sign-up respond
Parameters
_responseStatus ENUM status of back-end result
_buffer the buffer in which msg to be send
Returns
on success message length. on fail -1
Definition at line 65 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_SIGNUP, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicBE_ErrorFunc().