comm/protocol.c File Reference
#include <stdlib.h>
*
#include <string.h>
*
#include <stdio.h>
*
#include <err.h>
*
#include <sys/socket.h>
*
#include <netinet/in.h>
*
#include <arpa/inet.h>
*
#include `defines.h`
*
#include `Protocol.h`
*
#include `tlv.h`
*
Functions
int Protocol_EncodeSignUp (const char *_newUserName, const char *_password, void *_buffer)
The function Encode Message to Protocol format.
int Protocol_EncodeSignUp_Response (BackEndStatus _responseStatus, void *_buffer)
encode the response from server-end to front-end of sign-up respond
int Protocol_EncodeLogIn (const char *_userName, const char *_password, void *_buffer)
The function Encode Message to Protocol format.
int Protocol_EncodeLogIn_Response (BackEndStatus _responseStatus, void *_buffer)
encode the response from server-end to front-end of log-in respond
int Protocol_DecodeClient (void *_dataToDecode, size_t _lenght, ClientReceiveMessage_t *_message)
The function Decode Message from Protocol format to ClientReceiveMessage_t form.
bool Protocol_DecodeServer (void *_dataToDecode, size_t _lenght, ServerReceiveMessage_t *_message)
The function Decode Message from Protocol format to ServerReceiveMessage_t form.
int Protocol_EncodeNewGroup (const char *_groupName, void *_buffer)
The function Encode Message to Protocol format.
int Protocol_EncodeNewGroup_Response (BackEndStatus _responseStatus, sockaddr_in_t m_groupAdrres, void *_buffer)
encode the response from server-end to front-end of create new group respond
int Protocol_EncodeJoinGroup (const char *_groupNameToJoin, void *_buffer)
The function Encode Message to Protocol format.
int Protocol_EncodeJoinGroup_Response (BackEndStatus _responseStatus, sockaddr_in_t m_groupAdrres, void *_buffer)
encode the response from server-end to front-end of join group respond
int Protocol_EncodeGetAllGroups (void *_buffer)
The function Encode Message to Protocol format.
int Protocol_EncodeGetAllGroups_Response (BackEndStatus _responseStatus, const char *_groupsNames, size_t _numGroups, void *_buffer)
encode the response from server-end to front-end of show all group respond
Function Documentation
int Protocol_DecodeClient (void * _dataToDecode, size_t _lenght, ClientReceiveMessage_t * _message)
The function Decode Message from Protocol format to ClientReceiveMessage_t form.
Parameters
void* _dataToDecode - pointer to data that need to decoded
size_t _length - Data length
ClientReceiveMessage_t* _message - Receive Message that the function fill
Returns
bool on success true 1, on fail false 0.
Definition at line 134 of file protocol.c.
References BackEnd_SUCCESS, DELIMITER, DELIMITER_LENGHT, FALSE, GEN_ERROR, ClientReceiveMessage::m_messageType, ClientReceiveMessage::m_status, MAX_MESSAGE_LENGTH, MESSAGETYPE_CREATE_GROUP, MESSAGETYPE_DELETE_USER, MESSAGETYPE_GET_ALL_GROUPS, MESSAGETYPE_JOIN_GROUP, MESSAGETYPE_LEAVE_GROUP, MESSAGETYPE_LOGIN, MESSAGETYPE_LOGOUT, MESSAGETYPE_RESPONS, MESSAGETYPE_SIGNUP, TLV_decode(), TLV_MORE_TLVS_TO_DECODE, TLV_SUCCESS, and TRUE.
Referenced by LogicFE_GetAllGroupsName(), and main().
bool Protocol_DecodeServer (void * _dataToDecode, size_t _lenght, ServerReceiveMessage_t * _message)
The function Decode Message from Protocol format to ServerReceiveMessage_t form.
Parameters
void* _dataToDecode - pointer to data that need to decoded
size_t _length - Data length
ServerReceiveMessage_t* _message - Receive Message that the function fill
Returns
bool on success true 1, on fail false 0.
Definition at line 206 of file protocol.c.
References DELIMITER, DELIMITER_LENGHT, FALSE, GEN_ERROR, ServerReceiveMessage::m_groupName, ServerReceiveMessage::m_MessageType, ServerReceiveMessage::m_password, ServerReceiveMessage::m_userName, MAX_MESSAGE_LENGTH, MESSAGETYPE_CREATE_GROUP, MESSAGETYPE_DELETE_USER, MESSAGETYPE_GET_ALL_GROUPS, MESSAGETYPE_JOIN_GROUP, MESSAGETYPE_LEAVE_GROUP, MESSAGETYPE_LOGIN, MESSAGETYPE_LOGOUT, MESSAGETYPE_RESPONS, MESSAGETYPE_SIGNUP, TLV_decode(), TLV_MORE_TLVS_TO_DECODE, TLV_SUCCESS, and TRUE.
Referenced by LogicBE_ReciveDataFunc(), and main().
int Protocol_EncodeGetAllGroups (void * _buffer)
The function Encode Message to Protocol format.
Parameters
void* _buffer - Buffer that in which the message will written
Returns
on success message length. on fail -1
Definition at line 364 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_GET_ALL_GROUPS, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicFE_GetAllGroupsName().
int Protocol_EncodeGetAllGroups_Response (BackEndStatus _responseStatus, const char * _groupsNames, size_t _numGroups, void * _buffer)
encode the response from server-end to front-end of show all group respond
Parameters
_responseStatus ENUM status of back-end response
_groupsNames a string of groups names devided by \0
_numGroups the numer of groups in _groupsNames
_buffer the buffer in which msg to be send
Returns
on success message length. on fail -1
Definition at line 387 of file protocol.c.
References DELIMITER, DELIMITER_LENGHT, FALSE, GEN_ERROR, ClientReceiveMessage::m_groupAdrres, ClientReceiveMessage::m_GroupName, ClientReceiveMessage::m_numberOfGroups, MAX_MESSAGE_LENGTH, MESSAGETYPE_GET_ALL_GROUPS, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, TLV_SUCCESS, and TRUE.
Referenced by LogicBE_ErrorFunc().
int Protocol_EncodeJoinGroup (const char * _groupNameToJoin, void * _buffer)
The function Encode Message to Protocol format.
Parameters
Char* _groupNameToJoin - group name to join
void* _buffer - Buffer that in which the message will written
Returns
on success message length. on fail -1
Definition at line 318 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_JOIN_GROUP, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicFE_JoinGroup().
int Protocol_EncodeJoinGroup_Response (BackEndStatus _responseStatus, sockaddr_in_t m_groupAdrres, void * _buffer)
encode the response from server-end to front-end of join group respond
Parameters
_responseStatus ENUM status of back-end result
m_groupAdrres a struct that continues ip and port
_buffer the buffer in which msg to be send
Returns
on success message length. on fail -1
Definition at line 341 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_JOIN_GROUP, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicBE_ErrorFunc().
int Protocol_EncodeLogIn (const char * _userName, const char * _password, void * _buffer)
The function Encode Message to Protocol format.
Parameters
Char* _userName - User Name
Char* _password - Password
void* _buffer - Buffer that in which the message will written
Returns
on success message length. on fail -1
Definition at line 88 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_LOGIN, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicFE_Login().
int Protocol_EncodeLogIn_Response (BackEndStatus _responseStatus, void * _buffer)
encode the response from server-end to front-end of log-in respond
Parameters
_responseStatus ENUM status of back-end result
_buffer the buffer in which msg to be send
Returns
on success message length. on fail -1
Definition at line 111 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_LOGIN, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicBE_ErrorFunc().
int Protocol_EncodeNewGroup (const char * _groupName, void * _buffer)
The function Encode Message to Protocol format.
Parameters
Char* _groupName - group name
void* _buffer - Buffer that in which the message will written
Returns
on success message length. on fail -1
Definition at line 272 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_CREATE_GROUP, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicFE_CreateGroup().
int Protocol_EncodeNewGroup_Response (BackEndStatus _responseStatus, sockaddr_in_t m_groupAdrres, void * _buffer)
encode the response from server-end to front-end of create new group respond
Parameters
_responseStatus ENUM status of back-end result
m_groupAdrres a struct that continues ip and port
_buffer the buffer in which msg to be send
Returns
on success message length. on fail -1
Definition at line 295 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_CREATE_GROUP, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicBE_ErrorFunc().
int Protocol_EncodeSignUp (const char * _newUserName, const char * _password, void * _buffer)
The function Encode Message to Protocol format.
Parameters
Char* _newUserName - User Name
Char* _password - Password
void* _buffer - Buffer that in which the message will written
Returns
on success message length. on fail -1
Definition at line 41 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_SIGNUP, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicFE_Signup(), and main().
int Protocol_EncodeSignUp_Response (BackEndStatus _responseStatus, void * _buffer)
encode the response from server-end to front-end of sign-up respond
Parameters
_responseStatus ENUM status of back-end result
_buffer the buffer in which msg to be send
Returns
on success message length. on fail -1
Definition at line 65 of file protocol.c.
References DELIMITER, GEN_ERROR, MAX_MESSAGE_LENGTH, MESSAGETYPE_SIGNUP, TLV_encoder(), TLV_MORE_TLVS_TO_DECODE, and TLV_SUCCESS.
Referenced by LogicBE_ErrorFunc().