ds/queue.c File Reference
#include <assert.h>
*
#include <pthread.h>
*
#include <semaphore.h>
*
#include <stdbool.h>
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include `queue.h`
*
Data Structures
struct DSQueue
Functions
struct DSQueue * ds_queue_create (uint32_t buffer_capacity)
void ds_queue_free (struct DSQueue *queue)
int ds_queue_length (struct DSQueue *queue)
int ds_queue_capacity (struct DSQueue *queue)
void ds_queue_close (struct DSQueue *queue)
void ds_queue_put (struct DSQueue *queue, void *item)
void * ds_queue_get (struct DSQueue *queue)
Function Documentation
int ds_queue_capacity (struct DSQueue * queue)
Definition at line 98 of file queue.c.
References DSQueue::capacity.
Referenced by IP_Handle_Release().
void ds_queue_close (struct DSQueue * queue)
Definition at line 104 of file queue.c.
References DSQueue::closed, DSQueue::cond_length, and DSQueue::mutate.
struct DSQueue* ds_queue_create (uint32_t buffer_capacity)
Definition at line 40 of file queue.c.
References DSQueue::buf, DSQueue::capacity, DSQueue::closed, DSQueue::cond_length, DSQueue::length, DSQueue::mutate, and DSQueue::pos.
Referenced by IP_Handle_Create().
void ds_queue_free (struct DSQueue * queue)
Definition at line 71 of file queue.c.
References DSQueue::buf, DSQueue::cond_length, and DSQueue::mutate.
Referenced by IP_Handle_Destory().
void* ds_queue_get (struct DSQueue * queue)
Definition at line 132 of file queue.c.
References DSQueue::buf, DSQueue::capacity, DSQueue::closed, DSQueue::cond_length, DSQueue::length, DSQueue::mutate, and DSQueue::pos.
Referenced by IP_Handle_Destory(), and IP_Handle_GetFreeIP().
int ds_queue_length (struct DSQueue * queue)
Definition at line 88 of file queue.c.
References DSQueue::length, and DSQueue::mutate.
Referenced by IP_Handle_Destory(), IP_Handle_GetFreeIP(), and IP_Handle_Release().
void ds_queue_put (struct DSQueue * queue, void * item)
Definition at line 113 of file queue.c.
References DSQueue::buf, DSQueue::capacity, DSQueue::closed, DSQueue::cond_length, DSQueue::length, DSQueue::mutate, and DSQueue::pos.
Referenced by IP_Handle_Release().