comm/tcp/server/server.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <signal.h>
*
#include <unistd.h>
*
#include `tcp.h`
*
Macros
#define MAX_CONNECTIONS_ALLWAED 1000
Typedefs
typedef void(* sigHandler) (int sig, siginfo_t *siginfo, void *context)
Functions
void sigAbortHandler (int sig, siginfo_t *siginfo, void *context)
bool signalHangelSet (sigHandler _func)
int MyFunc (void *_data, size_t _sizeData, uint _socketNum, void *_contex)
int ActivateServer (int argc, char *argv[])
Variables
TCP_S_t * g_tcp = NULL
Macro Definition Documentation
#define MAX_CONNECTIONS_ALLWAED 1000
Definition at line 19 of file server.c.
Referenced by ActivateServer().
Typedef Documentation
typedef void(* sigHandler) (int sig, siginfo_t *siginfo, void *context)
Definition at line 21 of file server.c.
Function Documentation
int ActivateServer (int argc, char * argv[])
Definition at line 70 of file server.c.
References MAX_CONNECTIONS_ALLWAED, MyFunc(), sigAbortHandler(), signalHangelSet(), TCP_CreateServer(), TCP_DestroyServer(), and TCP_RunServer().
int MyFunc (void * _data, size_t _sizeData, uint _socketNum, void * _contex)
Definition at line 56 of file server.c.
References FALSE, TCP_Send(), and TRUE.
Referenced by ActivateServer().
void sigAbortHandler (int sig, siginfo_t * siginfo, void * context)
Definition at line 22 of file server.c.
References TCP_StopServer().
Referenced by ActivateServer().
bool signalHangelSet (sigHandler _func)
Definition at line 32 of file server.c.
References FALSE, and TRUE.
Referenced by ActivateServer().
Variable Documentation
TCP_S_t* g_tcp = NULL
Definition at line 17 of file server.c.