comm/tcp/src/tcp_client.h File Reference
Macros
#define TRUE 1
#define FALSE 0
Typedefs
typedef unsigned int uint
A TCP client ADT for future projects use.
typedef int bool
typedef struct TCP_C TCP_C_t
Functions
TCP_C_t * TCP_CreateClient (char *_ServerIP, uint _serverPort)
Create all is needed for a TCP client to connect to the server.
void TCP_DestroyClient (TCP_C_t *_TCP)
Cleans up and free after the program. This include the disconnect function inside it.
int TCP_ClientSend (TCP_C_t *_TCP, void *_msg, uint _msgLength)
Function to send data (back?) to a client.
int TCP_ClientRecive (TCP_C_t *_TCP, void *_buffer, uint _bufferMaxLength)
Function to invoke data read from clients without looping. just a singal read.
Macro Definition Documentation
#define FALSE 0
Definition at line 16 of file tcp_client.h.
#define TRUE 1
Definition at line 15 of file tcp_client.h.
Typedef Documentation
typedef int bool
Definition at line 14 of file tcp_client.h.
typedef struct TCP_C TCP_C_t
Definition at line 19 of file tcp_client.h.
typedef unsigned int uint
A TCP client ADT for future projects use.
Author
Yuval Hamberg
Date
Jul 4, 2017
Bug
Bug
Definition at line 13 of file tcp_client.h.
Function Documentation
int TCP_ClientRecive (TCP_C_t * _TCP, void * _buffer, uint _bufferMaxLength)
Function to invoke data read from clients without looping. just a singal read.
Parameters
_TCP a pointer to the TCP struct
_buffer the data buffer to be read to. up to BUFFER_MAX_SIZE bytes.
_bufferMaxLength the data buffer max size.
Returns
positive number represent the number of bytes read. negative number represent error.
Definition at line 180 of file tcp_client.c.
References ALIVE_MAGIC_NUMBER, GENERAL_ERROR, IsStructValid(), TCP_C::m_commSocket, TCP_C::m_connectedNum, TCP_C::m_magicNumber, and sanity_check().
Referenced by LogicFE_GetAllGroupsName(), and main().
int TCP_ClientSend (TCP_C_t * _TCP, void * _msg, uint _msgLength)
Function to send data (back?) to a client.
Parameters
_TCP a pointer to the TCP struct
_msg the data to be send. up to BUFFER_MAX_SIZE bytes.
_msgLength the data send size.
Returns
positive number represent the number of bytes send. negative number represent error.
Definition at line 158 of file tcp_client.c.
References GENERAL_ERROR, IsStructValid(), and TCP_C::m_commSocket.
Referenced by LogicFE_GetAllGroupsName(), and main().
TCP_C_t* TCP_CreateClient (char * _ServerIP, uint _serverPort)
Create all is needed for a TCP client to connect to the server.
Parameters
_ServerIP the ip address (ipv4 or ipv6) of the server
_serverPort the listning for new connection port on the server
Returns
pointer to the newly create struct
Definition at line 64 of file tcp_client.c.
References ALIVE_MAGIC_NUMBER, FALSE, TCP_C::m_commSocket, TCP_C::m_connectedNum, TCP_C::m_magicNumber, TCP_C::m_serverIP, TCP_C::m_serverPort, and TCP_ClientConnect().
Referenced by main(), and WhatDownClientApp_Create().
void TCP_DestroyClient (TCP_C_t * _TCP)
Cleans up and free after the program. This include the disconnect function inside it.
Parameters
_TCP pointer to the struct
Returns
void. silent fail.
Definition at line 110 of file tcp_client.c.
References DEAD_MAGIC_NUMBER, IsStructValid(), TCP_C::m_commSocket, and TCP_C::m_magicNumber.
Referenced by main().