comm/tcp/src/tcp.h File Reference
#include `sys/types.h`
*
Macros
#define MAX_CLIENTS_NUM 1000
A TCP server and client ADT for future projects use.
#define BUFFER_MAX_SIZE 1024
#define TRUE 1
#define FALSE 0
Typedefs
typedef unsigned int uint
typedef int bool
typedef enum TCP_SERVER_USER_ERROR TCP_SERVER_USER_ERROR
typedef int(* userActionFunc) (void *_data, size_t _sizeData, uint _socketNum, void *_contex)
typedef int(* clientConnectionChangeFunc) (uint _socketNum, void *_contex)
typedef int(* errorFunc) (TCP_SERVER_USER_ERROR _status, uint _socketNum, void *_contex)
typedef struct TCP_S TCP_S_t
Enumerations
enum TCP_SERVER_USER_ERROR { TOO_MANY_CONNECTION = 1
 }
Functions
TCP_S_t * TCP_CreateServer (uint _port, const char *_serverIP, uint _maxConnections, uint _timeoutMS, userActionFunc _reciveDataFunc, clientConnectionChangeFunc _newClientConnected, clientConnectionChangeFunc _clientDissconected, errorFunc _errorFunc, void *_contex)
Create the server and setup all is needed of work.
void TCP_DestroyServer (TCP_S_t *_TCP)
Cleans up and free after the program.
bool TCP_RunServer (TCP_S_t *_TCP)
start the server. it will loop around waiting for information to arrive or new connection request. When such occures, the user's userActionFunc _reciveDataFunc is actived. Iternal loop until ServerStop is called.
bool TCP_StopServer (TCP_S_t *_TCP)
stop the TCP_RunServer loop.
int TCP_Send (uint _socketNum, void *_msg, uint _msgLength)
Function to send data (back?) to a client.
int TCP_Recive (uint _socketNum, void *_buffer, uint _bufferMaxLength)
Function to invoke data read from clients without looping. just a singal read.
Macro Definition Documentation
#define BUFFER_MAX_SIZE 1024
Definition at line 20 of file tcp.h.
Referenced by TCP_Recive(), and TCP_RunServer().
#define FALSE 0
Definition at line 25 of file tcp.h.
Referenced by GetAllGruopFunction(), GroupsHandel_GetGroupAddres(), GroupsHandel_GetGroupsName(), GroupsHandel_IsGroupExist(), GroupsHandel_JoinGroup(), GroupsHandel_NewGroup(), IP_Handle_Release(), LogicBE_ErrorFunc(), LogicBE_SetServerPTR(), LogicFE_GetAllGroupsName(), LoginFunction(), MyFunc(), Protocol_DecodeClient(), Protocol_DecodeServer(), Protocol_EncodeGetAllGroups_Response(), signalHangelSet(), SignupFunction(), TCP_ClientConnect(), TCP_CreateClient(), TCP_Recive(), TCP_RunServer(), TCP_StopServer(), Ui_Run(), UsersHandle_AddNewUser(), UsersHandle_IsUserExist(), UsersHandle_IsUserPasswordMatch(), WhatDownBackEndApp_Run(), WhatDownBackEndApp_Stop(), and WhatDownClientApp_Stop().
#define MAX_CLIENTS_NUM 1000
A TCP server and client ADT for future projects use.
Author
Yuval Hamberg
Date
Jul 4, 2017
Bug
Bug not a possible TCP_SERVER_USER_ERROR were included.
when calling stop Server function and server is waiting on select nothing would happen until next transmission would arrive
timeout function has some undefined behavior
Definition at line 19 of file tcp.h.
#define TRUE 1
Definition at line 24 of file tcp.h.
Referenced by GetAllGruopFunction(), GroupsHandel_GetGroupsName(), GroupsHandel_IsGroupExist(), GroupsHandel_JoinGroup(), GroupsHandel_NewGroup(), IP_Handle_Release(), LogicBE_ErrorFunc(), LogicBE_ReciveDataFunc(), LogicBE_SetServerPTR(), LogicFE_GetAllGroupsName(), LoginFunction(), main(), MyFunc(), Protocol_DecodeClient(), Protocol_DecodeServer(), Protocol_EncodeGetAllGroups_Response(), signalHangelSet(), SignupFunction(), TCP_ClientConnect(), TCP_Recive(), TCP_RunServer(), TCP_StopServer(), UDP_MultiCast_Reciver_Create(), Ui_Run(), UsersHandle_AddNewUser(), UsersHandle_Destroy(), UsersHandle_IsUserExist(), UsersHandle_IsUserPasswordMatch(), and WhatDownClientApp_Run().
Typedef Documentation
typedef int bool
Definition at line 23 of file tcp.h.
typedef int(* clientConnectionChangeFunc) (uint _socketNum, void *_contex)
Definition at line 32 of file tcp.h.
typedef int(* errorFunc) (TCP_SERVER_USER_ERROR _status, uint _socketNum, void *_contex)
Definition at line 33 of file tcp.h.
typedef struct TCP_S TCP_S_t
Definition at line 36 of file tcp.h.
typedef enum TCP_SERVER_USER_ERROR TCP_SERVER_USER_ERROR
typedef unsigned int uint
Definition at line 22 of file tcp.h.
typedef int(* userActionFunc) (void *_data, size_t _sizeData, uint _socketNum, void *_contex)
Definition at line 31 of file tcp.h.
Enumeration Type Documentation
enum TCP_SERVER_USER_ERROR
Enumerator
TOO_MANY_CONNECTION
Definition at line 27 of file tcp.h.
Function Documentation
[TCP_CreateServer(uint _port, const char *_serverIP, uint _maxConnections, uint _timeoutMS, userActionFunc _reciveDataFunc, clientConnectionChangeFunc _newClientConnected, clientConnectionChangeFunc _clientDissconected, errorFunc _errorFunc, void *_contex)]TCP_S_t* TCP_CreateServer (uint _port, const char * _serverIP, uint _maxConnections, uint _timeoutMS, userActionFunc _reciveDataFunc, clientConnectionChangeFunc _newClientConnected, clientConnectionChangeFunc _clientDissconected, errorFunc _errorFunc, void * _contex)
Create the server and setup all is needed of work.
Parameters
_port the server listing port for new client connections.
_serverIP The server IP address in case of a few interfaces for the same computer. Can be left NULL for defualt ip selected.
_maxConnections if more connection than this number are simultansly try to connect, clients would be dealt and probably droped.
_timeoutMS any connection not used for this amount of time (miliSeconds) would be droped
_reciveDataFunc user function to invoke when data is recived at server
_newClientConnected user function to invoke when new client is connected. can be left NULL.
_clientDissconected user function to invoke when client is disconnected, either because of server of client induces. can be left NULL.
_errorFunc user function to invoke when errors occur in server. can be left NULL.
Returns
a pointer to the struct. NULL if failed.
Definition at line 121 of file tcp.c.
References ALIVE_MAGIC_NUMBER, list_new(), TCP_S::m_closedConnectionFunc, TCP_S::m_connectedNum, TCP_S::m_connectionCapacity, TCP_S::m_contex, TCP_S::m_errorFunc, TCP_S::m_listenSocket, TCP_S::m_magicNumber, TCP_S::m_newConnectionFunc, TCP_S::m_reciveDataFunc, TCP_S::m_serverIP, TCP_S::m_serverPort, TCP_S::m_sockets, and TCP_S::m_timeoutMS.
Referenced by ActivateServer(), and WhatDownBackEndApp_Create().
void TCP_DestroyServer (TCP_S_t * _TCP)
Cleans up and free after the program.
Parameters
_TCP pointer to the struct
Returns
void. silent fail.
Definition at line 184 of file tcp.c.
References DEAD_MAGIC_NUMBER, IsStructValid(), list_destroy(), LIST_HEAD, list_iterator_new(), list_iterator_next(), TCP_S::m_listenSocket, TCP_S::m_magicNumber, and TCP_S::m_sockets.
Referenced by ActivateServer(), LogicBE_Destroy(), and WhatDownBackEndApp_Destroy().
int TCP_Recive (uint _socketNum, void * _buffer, uint _bufferMaxLength)
Function to invoke data read from clients without looping. just a singal read.
Parameters
_socketNum a number representing the client the information would be read from.
_buffer the data buffer to be read to. up to BUFFER_MAX_SIZE bytes.
_bufferMaxLength the data buffer max size.
Returns
positive number represent the number of bytes read. negative number represent error.
Definition at line 295 of file tcp.c.
References ALIVE_MAGIC_NUMBER, BACK_LOG_CAPACITY, BUFFER_MAX_SIZE, FALSE, GENERAL_ERROR, IS_NON_BLOCKING_METHOD, IsStructValid(), list_at(), LIST_HEAD, list_iterator_new(), list_iterator_next(), list_lpush(), list_node_new(), list_remove(), list_rpush(), TCP_S::m_closedConnectionFunc, TCP_S::m_connectedNum, TCP_S::m_connectionCapacity, TCP_S::m_contex, TCP_S::m_errorFunc, TCP_S::m_isServerRun, TCP_S::m_listenSocket, TCP_S::m_magicNumber, SocketInfo::m_magicNumber, TCP_S::m_newConnectionFunc, TCP_S::m_reciveDataFunc, TCP_S::m_serverIP, TCP_S::m_serverPort, SocketInfo::m_socketFD, TCP_S::m_sockets, TCP_S::m_timeoutMS, SocketInfo::m_timeToDie, sanity_check(), SI_MAGIC_NUMBER, TCP_Recive(), TOO_MANY_CONNECTION, TRUE, and list_node::val.
Referenced by TCP_Recive(), and TCP_RunServer().
bool TCP_RunServer (TCP_S_t * _TCP)
start the server. it will loop around waiting for information to arrive or new connection request. When such occures, the user's userActionFunc _reciveDataFunc is actived. Iternal loop until ServerStop is called.
Parameters
_TCP pointer to the struct
Returns
the status of return. TRUE when stopped normally or FALSE when failed to run.
Definition at line 212 of file tcp.c.
References BUFFER_MAX_SIZE, FALSE, IS_NON_BLOCKING_METHOD, IsStructValid(), LIST_HEAD, list_iterator_new(), list_iterator_next(), TCP_S::m_contex, TCP_S::m_isServerRun, TCP_S::m_reciveDataFunc, TCP_S::m_sockets, TCP_Recive(), and TRUE.
Referenced by ActivateServer(), and WhatDownBackEndApp_Run().
int TCP_Send (uint _socketNum, void * _msg, uint _msgLength)
Function to send data (back?) to a client.
Parameters
_socketNum a number representing the client the information would be send to.
_msg the data to be send. up to BUFFER_MAX_SIZE bytes.
_msgLength the data send size.
Returns
positive number represent the number of bytes send. negative number represent error.
Definition at line 275 of file tcp.c.
References GENERAL_ERROR.
Referenced by LogicBE_ErrorFunc(), and MyFunc().
bool TCP_StopServer (TCP_S_t * _TCP)
stop the TCP_RunServer loop.
Parameters
_TCP a pointer to the TCP server struct
Returns
bool TRUE 1 is success or FALSE 0 if failed.
Definition at line 265 of file tcp.c.
References FALSE, IsStructValid(), TCP_S::m_isServerRun, and TRUE.
Referenced by sigAbortHandler(), and WhatDownBackEndApp_Stop().