comm/tcp/src/tcp_client.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <sys/socket.h>
*
#include <arpa/inet.h>
*
#include <unistd.h>
*
#include `defines.h`
*
#include `list.h`
*
#include `tcp_client.h`
*
Data Structures
struct TCP_C
Macros
#define ALIVE_MAGIC_NUMBER 0xfadeface
#define DEAD_MAGIC_NUMBER 0xdeadface
#define GENERAL_ERROR -9
#define BACK_LOG_CAPACITY 128
Functions
int TCP_ClientGetSocket (TCP_C_t *_TCP)
If the client need to know the server socket it is connected to.
bool TCP_ClientConnect (TCP_C_t *_TCP)
TCP_C_t * TCP_CreateClient (char *_ServerIP, uint _serverPort)
Create all is needed for a TCP client to connect to the server.
void TCP_DestroyClient (TCP_C_t *_TCP)
Cleans up and free after the program. This include the disconnect function inside it.
int TCP_ClientSend (TCP_C_t *_TCP, void *_msg, uint _msgLength)
Function to send data (back?) to a client.
int TCP_ClientRecive (TCP_C_t *_TCP, void *_buffer, uint _bufferMaxLength)
Function to invoke data read from clients without looping. just a singal read.
Macro Definition Documentation
#define ALIVE_MAGIC_NUMBER 0xfadeface
Definition at line 23 of file tcp_client.c.
Referenced by TCP_ClientRecive(), and TCP_CreateClient().
#define BACK_LOG_CAPACITY 128
Definition at line 27 of file tcp_client.c.
#define DEAD_MAGIC_NUMBER 0xdeadface
Definition at line 24 of file tcp_client.c.
Referenced by TCP_DestroyClient().
#define GENERAL_ERROR -9
Definition at line 26 of file tcp_client.c.
Referenced by TCP_ClientGetSocket(), TCP_ClientRecive(), and TCP_ClientSend().
Function Documentation
bool TCP_ClientConnect (TCP_C_t * _TCP)
Definition at line 127 of file tcp_client.c.
References FALSE, TCP_C::m_commSocket, TCP_C::m_connectedNum, TCP_C::m_serverIP, TCP_C::m_serverPort, and TRUE.
Referenced by TCP_CreateClient().
int TCP_ClientGetSocket (TCP_C_t * _TCP)
If the client need to know the server socket it is connected to.
Parameters
_TCP the pointer to the client struct
Returns
int that represent the file descriptor (socket) of this client
Definition at line 148 of file tcp_client.c.
References GENERAL_ERROR, IsStructValid(), and TCP_C::m_commSocket.
int TCP_ClientRecive (TCP_C_t * _TCP, void * _buffer, uint _bufferMaxLength)
Function to invoke data read from clients without looping. just a singal read.
Parameters
_TCP a pointer to the TCP struct
_buffer the data buffer to be read to. up to BUFFER_MAX_SIZE bytes.
_bufferMaxLength the data buffer max size.
Returns
positive number represent the number of bytes read. negative number represent error.
Definition at line 180 of file tcp_client.c.
References ALIVE_MAGIC_NUMBER, GENERAL_ERROR, IsStructValid(), TCP_C::m_commSocket, TCP_C::m_connectedNum, TCP_C::m_magicNumber, and sanity_check().
Referenced by LogicFE_GetAllGroupsName(), and main().
int TCP_ClientSend (TCP_C_t * _TCP, void * _msg, uint _msgLength)
Function to send data (back?) to a client.
Parameters
_TCP a pointer to the TCP struct
_msg the data to be send. up to BUFFER_MAX_SIZE bytes.
_msgLength the data send size.
Returns
positive number represent the number of bytes send. negative number represent error.
Definition at line 158 of file tcp_client.c.
References GENERAL_ERROR, IsStructValid(), and TCP_C::m_commSocket.
Referenced by LogicFE_GetAllGroupsName(), and main().
TCP_C_t* TCP_CreateClient (char * _ServerIP, uint _serverPort)
Create all is needed for a TCP client to connect to the server.
Parameters
_ServerIP the ip address (ipv4 or ipv6) of the server
_serverPort the listning for new connection port on the server
Returns
pointer to the newly create struct
Definition at line 64 of file tcp_client.c.
References ALIVE_MAGIC_NUMBER, FALSE, TCP_C::m_commSocket, TCP_C::m_connectedNum, TCP_C::m_magicNumber, TCP_C::m_serverIP, TCP_C::m_serverPort, and TCP_ClientConnect().
Referenced by main(), and WhatDownClientApp_Create().
void TCP_DestroyClient (TCP_C_t * _TCP)
Cleans up and free after the program. This include the disconnect function inside it.
Parameters
_TCP pointer to the struct
Returns
void. silent fail.
Definition at line 110 of file tcp_client.c.
References DEAD_MAGIC_NUMBER, IsStructValid(), TCP_C::m_commSocket, and TCP_C::m_magicNumber.
Referenced by main().