comm/tcp/src/tcp.c File Reference
#include <netinet/in.h>
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include <sys/socket.h>
*
#include <sys/types.h>
*
#include <sys/time.h>
*
#include <sys/select.h>
*
#include <arpa/inet.h>
*
#include <string.h>
*
#include <fcntl.h>
*
#include <errno.h>
*
#include <unistd.h>
*
#include `defines.h`
*
#include `list.h`
*
#include `tcp.h`
*
Data Structures
struct TCP_S
struct SocketInfo
Macros
#define ALIVE_MAGIC_NUMBER 0xfadeface
#define DEAD_MAGIC_NUMBER 0xdeadface
#define SI_MAGIC_NUMBER 0xdeaddead
#define GENERAL_ERROR -9
#define BACK_LOG_CAPACITY 128
#define IS_NON_BLOCKING_METHOD FALSE
Typedefs
typedef struct timeval timeval_t
typedef struct SocketInfo SocketInfo_t
Functions
TCP_S_t * TCP_CreateServer (uint _port, const char *_serverIP, uint _maxConnections, uint _timeoutMS, userActionFunc _reciveDataFunc, clientConnectionChangeFunc _newClientConnected, clientConnectionChangeFunc _clientDissconected, errorFunc _errorFunc, void *_contex)
Create the server and setup all is needed of work.
void TCP_DestroyServer (TCP_S_t *_TCP)
Cleans up and free after the program.
bool TCP_RunServer (TCP_S_t *_TCP)
start the server. it will loop around waiting for information to arrive or new connection request. When such occures, the user's userActionFunc _reciveDataFunc is actived. Iternal loop until ServerStop is called.
bool TCP_StopServer (TCP_S_t *_TCP)
stop the TCP_RunServer loop.
int TCP_Send (uint _socketNum, void *_msg, uint _msgLength)
Function to send data (back?) to a client.
int TCP_Recive (uint _socketNum, void *_buffer, uint _bufferMaxLength)
Function to invoke data read from clients without looping. just a singal read.
Macro Definition Documentation
#define ALIVE_MAGIC_NUMBER 0xfadeface
Definition at line 27 of file tcp.c.
Referenced by TCP_CreateServer(), and TCP_Recive().
#define BACK_LOG_CAPACITY 128
Definition at line 32 of file tcp.c.
Referenced by TCP_Recive().
#define DEAD_MAGIC_NUMBER 0xdeadface
Definition at line 28 of file tcp.c.
Referenced by TCP_DestroyServer().
#define GENERAL_ERROR -9
Definition at line 31 of file tcp.c.
Referenced by TCP_Recive(), and TCP_Send().
#define IS_NON_BLOCKING_METHOD FALSE
Definition at line 35 of file tcp.c.
Referenced by TCP_Recive(), and TCP_RunServer().
#define SI_MAGIC_NUMBER 0xdeaddead
Definition at line 29 of file tcp.c.
Referenced by TCP_Recive().
Typedef Documentation
typedef struct SocketInfo SocketInfo_t
typedef struct timeval timeval_t
Definition at line 37 of file tcp.c.
Function Documentation
[TCP_CreateServer(uint _port, const char *_serverIP, uint _maxConnections, uint _timeoutMS, userActionFunc _reciveDataFunc, clientConnectionChangeFunc _newClientConnected, clientConnectionChangeFunc _clientDissconected, errorFunc _errorFunc, void *_contex)]TCP_S_t* TCP_CreateServer (uint _port, const char * _serverIP, uint _maxConnections, uint _timeoutMS, userActionFunc _reciveDataFunc, clientConnectionChangeFunc _newClientConnected, clientConnectionChangeFunc _clientDissconected, errorFunc _errorFunc, void * _contex)
Create the server and setup all is needed of work.
Parameters
_port the server listing port for new client connections.
_serverIP The server IP address in case of a few interfaces for the same computer. Can be left NULL for defualt ip selected.
_maxConnections if more connection than this number are simultansly try to connect, clients would be dealt and probably droped.
_timeoutMS any connection not used for this amount of time (miliSeconds) would be droped
_reciveDataFunc user function to invoke when data is recived at server
_newClientConnected user function to invoke when new client is connected. can be left NULL.
_clientDissconected user function to invoke when client is disconnected, either because of server of client induces. can be left NULL.
_errorFunc user function to invoke when errors occur in server. can be left NULL.
Returns
a pointer to the struct. NULL if failed.
Definition at line 121 of file tcp.c.
References ALIVE_MAGIC_NUMBER, list_new(), TCP_S::m_closedConnectionFunc, TCP_S::m_connectedNum, TCP_S::m_connectionCapacity, TCP_S::m_contex, TCP_S::m_errorFunc, TCP_S::m_listenSocket, TCP_S::m_magicNumber, TCP_S::m_newConnectionFunc, TCP_S::m_reciveDataFunc, TCP_S::m_serverIP, TCP_S::m_serverPort, TCP_S::m_sockets, and TCP_S::m_timeoutMS.
Referenced by ActivateServer(), and WhatDownBackEndApp_Create().
void TCP_DestroyServer (TCP_S_t * _TCP)
Cleans up and free after the program.
Parameters
_TCP pointer to the struct
Returns
void. silent fail.
Definition at line 184 of file tcp.c.
References DEAD_MAGIC_NUMBER, IsStructValid(), list_destroy(), LIST_HEAD, list_iterator_new(), list_iterator_next(), TCP_S::m_listenSocket, TCP_S::m_magicNumber, and TCP_S::m_sockets.
Referenced by ActivateServer(), LogicBE_Destroy(), and WhatDownBackEndApp_Destroy().
int TCP_Recive (uint _socketNum, void * _buffer, uint _bufferMaxLength)
Function to invoke data read from clients without looping. just a singal read.
Parameters
_socketNum a number representing the client the information would be read from.
_buffer the data buffer to be read to. up to BUFFER_MAX_SIZE bytes.
_bufferMaxLength the data buffer max size.
Returns
positive number represent the number of bytes read. negative number represent error.
Definition at line 295 of file tcp.c.
References ALIVE_MAGIC_NUMBER, BACK_LOG_CAPACITY, BUFFER_MAX_SIZE, FALSE, GENERAL_ERROR, IS_NON_BLOCKING_METHOD, IsStructValid(), list_at(), LIST_HEAD, list_iterator_new(), list_iterator_next(), list_lpush(), list_node_new(), list_remove(), list_rpush(), TCP_S::m_closedConnectionFunc, TCP_S::m_connectedNum, TCP_S::m_connectionCapacity, TCP_S::m_contex, TCP_S::m_errorFunc, TCP_S::m_isServerRun, TCP_S::m_listenSocket, TCP_S::m_magicNumber, SocketInfo::m_magicNumber, TCP_S::m_newConnectionFunc, TCP_S::m_reciveDataFunc, TCP_S::m_serverIP, TCP_S::m_serverPort, SocketInfo::m_socketFD, TCP_S::m_sockets, TCP_S::m_timeoutMS, SocketInfo::m_timeToDie, sanity_check(), SI_MAGIC_NUMBER, TCP_Recive(), TOO_MANY_CONNECTION, TRUE, and list_node::val.
Referenced by TCP_Recive(), and TCP_RunServer().
bool TCP_RunServer (TCP_S_t * _TCP)
start the server. it will loop around waiting for information to arrive or new connection request. When such occures, the user's userActionFunc _reciveDataFunc is actived. Iternal loop until ServerStop is called.
Parameters
_TCP pointer to the struct
Returns
the status of return. TRUE when stopped normally or FALSE when failed to run.
Definition at line 212 of file tcp.c.
References BUFFER_MAX_SIZE, FALSE, IS_NON_BLOCKING_METHOD, IsStructValid(), LIST_HEAD, list_iterator_new(), list_iterator_next(), TCP_S::m_contex, TCP_S::m_isServerRun, TCP_S::m_reciveDataFunc, TCP_S::m_sockets, TCP_Recive(), and TRUE.
Referenced by ActivateServer(), and WhatDownBackEndApp_Run().
int TCP_Send (uint _socketNum, void * _msg, uint _msgLength)
Function to send data (back?) to a client.
Parameters
_socketNum a number representing the client the information would be send to.
_msg the data to be send. up to BUFFER_MAX_SIZE bytes.
_msgLength the data send size.
Returns
positive number represent the number of bytes send. negative number represent error.
Definition at line 275 of file tcp.c.
References GENERAL_ERROR.
Referenced by LogicBE_ErrorFunc(), and MyFunc().
bool TCP_StopServer (TCP_S_t * _TCP)
stop the TCP_RunServer loop.
Parameters
_TCP a pointer to the TCP server struct
Returns
bool TRUE 1 is success or FALSE 0 if failed.
Definition at line 265 of file tcp.c.
References FALSE, IsStructValid(), TCP_S::m_isServerRun, and TRUE.
Referenced by sigAbortHandler(), and WhatDownBackEndApp_Stop().