comm/tlv.h File Reference
encoding / decodeing system for commanacation.
#include `defines.h`
*
#include `Protocol.h`
*
Macros
#define NDEBUG
#define TLV_LENGTH_LENGTH TLV_LENGTH_LENGHT			/* size in char of number that is the size of str information send. eg. 2 digits is 42 */
#define TLV_META_LENGTH HEADER_LENGTH
Typedefs
typedef enum TLV_Result TLV_Result
Enumerations
enum TLV_Result {
*
TLV_SUCCESS = 0,
TLV_MORE_TLVS_TO_DECODE,
TLV_TRANCATED_TLV,
TLV_NO_TLV_FOUND,
*
TLV_INPUT_ERROR,
TLV_UNKNOWN_ERROR,
TLV_UNKNOWN_TYPE,
TLV_ALLOCATION_ERROR
 }
Functions
TLV_Result TLV_encoder (char *_inputStr, char _dataType, Uint dataLenght, char *_tlvedString, Uint *_tlvedStringLength)
TLV_encoder.
TLV_Result TLV_decode (char *_TLV_String, Uint _TLV_StringLength, char *_decodedStr, Uint *_decodedStrLength, char *_datatypeFound, char **_nextTLV_Ptr, Uint *_nextTLV_Lenth)
TLV_decode.
Detailed Description
encoding / decodeing system for commanacation.
Type Legnth Value. a system to send and recive information. wraps varius type of info and varied size into package. functions are unsafe. inadaqunt space would result in undifined behiver.
Author
Author Yuval Hamberg (yuval.hamberg@gmail.com)
Date
April 2017
Bug
Bug No known bugs.
check that no str function are called that prevent non string information.
Macro Definition Documentation
#define NDEBUG
Definition at line 8 of file tlv.h.
#define TLV_LENGTH_LENGTH TLV_LENGTH_LENGHT			/* size in char of number that is the size of str information send. eg. 2 digits is 42 */
Definition at line 28 of file tlv.h.
Referenced by TLV_decode(), and TLV_encoder().
#define TLV_META_LENGTH HEADER_LENGTH
Definition at line 29 of file tlv.h.
Typedef Documentation
typedef enum TLV_Result TLV_Result
Enumeration Type Documentation
enum TLV_Result
Enumerator
TLV_SUCCESS
TLV_MORE_TLVS_TO_DECODE
TLV_TRANCATED_TLV
TLV_NO_TLV_FOUND
TLV_INPUT_ERROR
TLV_UNKNOWN_ERROR
TLV_UNKNOWN_TYPE
TLV_ALLOCATION_ERROR
Definition at line 32 of file tlv.h.
Function Documentation
TLV_Result TLV_decode (char * _TLV_String, Uint _TLV_StringLength, char * _decodedStr, Uint * _decodedStrLength, char * _datatypeFound, char ** _nextTLV_Ptr, Uint * _nextTLV_Lenth)
TLV_decode.
decode a stream of information.
[in] char* _TLV_String: the stream of information. [in] Uint _TLV_StringLength: the stream of information length in bytes.
[out] char* _decodedStr: the information inside the stream. [out] Uint* _decodedStrLength: the information inside the stream length in bytes.. [out] char* _datatypeFound: data type reprentation. [out] char** _nextTLV_Ptr: pointer to the next call if user wants. [out] Uint* _nextTLV_Lenth: the length in bytes of the next call.
Returns
check retuen values in above TLV_Result enum.
Return values
TLV_Result
Definition at line 53 of file tlv.c.
References TLV_INPUT_ERROR, TLV_LENGTH_LENGTH, TLV_MORE_TLVS_TO_DECODE, TLV_SUCCESS, TLV_TRANCATED_TLV, and TLV_TYPE_LENGTH.
Referenced by Protocol_DecodeClient(), and Protocol_DecodeServer().
TLV_Result TLV_encoder (char * _inputStr, char _dataType, Uint dataLenght, char * _tlvedString, Uint * _tlvedStringLength)
TLV_encoder.
encode a stream of information.
[in] char* _inputStr: information to be encoded [in] char _dataType: the type of information encoded [in] Uint dataLenght: the length of information in bytes.
[out] char* _tlvedString: the encoded information [out] Uint* _tlvedStringLength: the encoded information length in bytes.
Returns
check retuen values in above TLV_Result enum.
Return values
TLV_Result
Definition at line 26 of file tlv.c.
References TLV_INPUT_ERROR, TLV_LENGTH_LENGTH, TLV_SUCCESS, and TLV_UNKNOWN_ERROR.
Referenced by Protocol_EncodeGetAllGroups(), Protocol_EncodeGetAllGroups_Response(), Protocol_EncodeJoinGroup(), Protocol_EncodeJoinGroup_Response(), Protocol_EncodeLogIn(), Protocol_EncodeLogIn_Response(), Protocol_EncodeNewGroup(), Protocol_EncodeNewGroup_Response(), Protocol_EncodeSignUp(), and Protocol_EncodeSignUp_Response().