backEnd_src/usersHandle.h File Reference
#include `defines.h`
*
Typedefs
typedef struct UsersHandle UsersHandle_t
Functions
UsersHandle_t * UsersHandle_Create ()
create and setup
void UsersHandle_Destroy (UsersHandle_t *_usersHandel)
cleanup after the processing
int UsersHandle_AddNewUser (UsersHandle_t *_usersHandel, char *_userName, char *_password, char *_nickname, uint _premission, int _socketNum)
add a user to the the DS.
bool UsersHandle_RemoveUser (UsersHandle_t *_usersHandel, char *_userName)
remove the recorde of a user from the ds
int UsersHandle_CountUsers (UsersHandle_t *_usersHandel)
how many users in ds. NOT IMPLEMENTED
bool UsersHandle_IsUserExist (UsersHandle_t *_usersHandel, char *_userName)
checks if the user already exist
bool UsersHandle_IsUserPasswordMatch (UsersHandle_t *_usersHandel, const char *_userName, const char *_password)
check if for a certain user, this is the password. used for login.
Typedef Documentation
typedef struct UsersHandle UsersHandle_t
Definition at line 17 of file usersHandle.h.
Function Documentation
int UsersHandle_AddNewUser (UsersHandle_t * _usersHandel, char * _userName, char * _password, char * _nickname, uint _premission, int _socketNum)
add a user to the the DS.
Parameters
_usersHandel the pointer to the struct
_userName the new user username.
_password the new user password.
_nickname the new user display name in chats. NOT IMPLEMENTED
_premission the level of premission the user has. which group can he join. NOT IMPLEMENTED
_socketNum the identifier of the user for this session.
Returns
TRUE for success. FALSE for fail. might fail if username taken, null inputs and more.
Definition at line 88 of file usersHandle.c.
References CreateValue(), ds_hashmap_put_str(), FALSE, IsStructValid(), UsersHandle::m_continer, TRUE, and UsersHandle_IsUserExist().
Referenced by LogicBE_ErrorFunc().
int UsersHandle_CountUsers (UsersHandle_t * _usersHandel)
how many users in ds. NOT IMPLEMENTED
Parameters
_usersHandel the pointer to the struct
Returns
the number of users. negative values for errors.
UsersHandle_t* UsersHandle_Create ()
create and setup
Returns
a pointer to the struct
Definition at line 51 of file usersHandle.c.
References ds_hashmap_create(), UsersHandle::m_continer, UsersHandle::m_magicNumber, and USERS_HANDLE_MAGIC_NUMBER.
Referenced by WhatDownBackEndApp_Create().
void UsersHandle_Destroy (UsersHandle_t * _usersHandel)
cleanup after the processing
Parameters
_usersHandel the pointer to the struct
Definition at line 73 of file usersHandle.c.
References ds_hashmap_free(), IsStructValid(), UsersHandle::m_continer, UsersHandle::m_magicNumber, and TRUE.
Referenced by WhatDownBackEndApp_Create(), and WhatDownBackEndApp_Destroy().
bool UsersHandle_IsUserExist (UsersHandle_t * _usersHandel, char * _userName)
checks if the user already exist
Parameters
_usersHandel the pointer to the struct
_userName the user username identifier.
Returns
bool answer. error return FALSE
Definition at line 113 of file usersHandle.c.
References ds_hashmap_get_str(), FALSE, IsStructValid(), UsersHandle::m_continer, and TRUE.
Referenced by LogicBE_ErrorFunc(), and UsersHandle_AddNewUser().
bool UsersHandle_IsUserPasswordMatch (UsersHandle_t * _usersHandel, const char * _userName, const char * _password)
check if for a certain user, this is the password. used for login.
Parameters
_usersHandel the pointer to the struct
_userName the user username identifier.
_password the password to check against
Returns
bool answer. error return FALSE
Definition at line 129 of file usersHandle.c.
References ds_hashmap_get_str(), FALSE, UsersHandle::m_continer, User::m_password, and TRUE.
Referenced by LogicBE_ErrorFunc().
bool UsersHandle_RemoveUser (UsersHandle_t * _usersHandel, char * _userName)
remove the recorde of a user from the ds
Parameters
_usersHandel the pointer to the struct
_userName the user username identifier.
Returns
TRUE for success. FALSE for fail. might fail if username taken, null inputs and more.