backEnd_src/usersHandle.c File Reference
#include <string.h>
*
#include `usersHandle.h`
*
#include `Protocol.h`
*
#include `hashmap.h`
*
Data Structures
struct UsersHandle
struct User
Macros
#define USERS_HANDLE_MAGIC_NUMBER 0xfacefade
#define USER_MAGIC_NUMBER 0xfaceabcd
#define CAPACITY 128
Typedefs
typedef struct User User_t
Functions
bool IsStructValid (UsersHandle_t *_usersHandel)
User_t * CreateValue (char *_userName, char *_password, char *_nickname, uint _premission, int _socketNum)
UsersHandle_t * UsersHandle_Create ()
create and setup
void UsersHandle_Destroy (UsersHandle_t *_usersHandel)
cleanup after the processing
int UsersHandle_AddNewUser (UsersHandle_t *_usersHandel, char *_userName, char *_password, char *_nickname, uint _premission, int _socketNum)
add a user to the the DS.
int UsersHandle_IsUserExist (UsersHandle_t *_usersHandel, char *_userName)
checks if the user already exist
int UsersHandle_IsUserPasswordMatch (UsersHandle_t *_usersHandel, const char *_userName, const char *_password)
check if for a certain user, this is the password. used for login.
Macro Definition Documentation
#define CAPACITY 128
Definition at line 18 of file usersHandle.c.
#define USER_MAGIC_NUMBER 0xfaceabcd
Definition at line 16 of file usersHandle.c.
Referenced by CreateValue().
#define USERS_HANDLE_MAGIC_NUMBER 0xfacefade
Definition at line 15 of file usersHandle.c.
Referenced by IsStructValid(), and UsersHandle_Create().
Typedef Documentation
typedef struct User User_t
Function Documentation
User_t * CreateValue (char * _userName, char * _password, char * _nickname, uint _premission, int _socketNum)
Definition at line 157 of file usersHandle.c.
References User::m_magicNumber, User::m_nickName, User::m_password, User::m_premission, User::m_socketNum, User::m_userName, MAX_PASSWORD, MAX_USERNAME, and USER_MAGIC_NUMBER.
Referenced by GroupsHandel_GetGroupsName(), GroupsHandel_NewGroup(), and UsersHandle_AddNewUser().
bool IsStructValid (UsersHandle_t * _usersHandel)
Definition at line 152 of file usersHandle.c.
References UsersHandle::m_magicNumber, and USERS_HANDLE_MAGIC_NUMBER.
Referenced by GroupsHandel_Destroy(), GroupsHandel_GetGroupAddres(), GroupsHandel_GetGroupsName(), GroupsHandel_IsGroupExist(), GroupsHandel_JoinGroup(), GroupsHandel_NewGroup(), IP_Handle_Destory(), IP_Handle_GetFreeIP(), IP_Handle_Release(), LogicBE_Destroy(), LogicBE_ErrorFunc(), LogicBE_ReciveDataFunc(), LogicBE_SetServerPTR(), LogicFE_CreateGroup(), LogicFE_GetAllGroupsName(), LogicFE_JoinGroup(), LogicFE_Login(), LogicFE_Signup(), TCP_ClientGetSocket(), TCP_ClientRecive(), TCP_ClientSend(), TCP_DestroyClient(), TCP_DestroyServer(), TCP_Recive(), TCP_RunServer(), TCP_StopServer(), UsersHandle_AddNewUser(), UsersHandle_Destroy(), UsersHandle_IsUserExist(), WhatDownBackEndApp_Destroy(), WhatDownBackEndApp_Run(), and WhatDownBackEndApp_Stop().
int UsersHandle_AddNewUser (UsersHandle_t * _usersHandel, char * _userName, char * _password, char * _nickname, uint _premission, int _socketNum)
add a user to the the DS.
Parameters
_usersHandel the pointer to the struct
_userName the new user username.
_password the new user password.
_nickname the new user display name in chats. NOT IMPLEMENTED
_premission the level of premission the user has. which group can he join. NOT IMPLEMENTED
_socketNum the identifier of the user for this session.
Returns
TRUE for success. FALSE for fail. might fail if username taken, null inputs and more.
Definition at line 88 of file usersHandle.c.
References CreateValue(), ds_hashmap_put_str(), FALSE, IsStructValid(), UsersHandle::m_continer, TRUE, and UsersHandle_IsUserExist().
Referenced by LogicBE_ErrorFunc().
UsersHandle_t* UsersHandle_Create ()
create and setup
Returns
a pointer to the struct
Definition at line 51 of file usersHandle.c.
References ds_hashmap_create(), UsersHandle::m_continer, UsersHandle::m_magicNumber, and USERS_HANDLE_MAGIC_NUMBER.
Referenced by WhatDownBackEndApp_Create().
void UsersHandle_Destroy (UsersHandle_t * _usersHandel)
cleanup after the processing
Parameters
_usersHandel the pointer to the struct
Definition at line 73 of file usersHandle.c.
References ds_hashmap_free(), IsStructValid(), UsersHandle::m_continer, UsersHandle::m_magicNumber, and TRUE.
Referenced by WhatDownBackEndApp_Create(), and WhatDownBackEndApp_Destroy().
int UsersHandle_IsUserExist (UsersHandle_t * _usersHandel, char * _userName)
checks if the user already exist
Parameters
_usersHandel the pointer to the struct
_userName the user username identifier.
Returns
bool answer. error return FALSE
Definition at line 113 of file usersHandle.c.
References ds_hashmap_get_str(), FALSE, IsStructValid(), UsersHandle::m_continer, and TRUE.
Referenced by LogicBE_ErrorFunc(), and UsersHandle_AddNewUser().
int UsersHandle_IsUserPasswordMatch (UsersHandle_t * _usersHandel, const char * _userName, const char * _password)
check if for a certain user, this is the password. used for login.
Parameters
_usersHandel the pointer to the struct
_userName the user username identifier.
_password the password to check against
Returns
bool answer. error return FALSE
Definition at line 129 of file usersHandle.c.
References ds_hashmap_get_str(), FALSE, UsersHandle::m_continer, User::m_password, and TRUE.
Referenced by LogicBE_ErrorFunc().