ds/vector.c File Reference
#include <stdlib.h>
*
#include <string.h>
*
#include `vector.h`
*
Functions
struct DSVector * ds_vector_create ()
struct DSVector * ds_vector_create_capacity (int32_t capacity)
void ds_vector_free (struct DSVector *vec)
void ds_vector_free_no_data (struct DSVector *vec)
struct DSVector * ds_vector_copy (struct DSVector *vec)
void ds_vector_append (struct DSVector *vec, void *data)
void ds_vector_insert (struct DSVector *vec, void *data, int32_t index)
void ds_vector_remove (struct DSVector *vec, int32_t index)
void * ds_vector_get (struct DSVector *vec, int32_t index)
void ds_vector_set (struct DSVector *vec, void *data, int32_t index)
void ds_vector_swap (struct DSVector *vec, int32_t i, int32_t j)
void ds_vector_map (struct DSVector *vec, void(func)(void *))
int32_t ds_vector_find (struct DSVector *vec, void *needle, int32_t(compare)(void *, void *))
void ds_vector_sort (struct DSVector *vec, int32_t(compare)(void *, void *))
Function Documentation
void ds_vector_append (struct DSVector * vec, void * data)
Adds an element to the end of a vector. Runs in constant time.
Definition at line 75 of file vector.c.
References DSVector::data, and DSVector::size.
Referenced by ds_hashmap_put_int(), and ds_vector_copy().
struct DSVector* ds_vector_copy (struct DSVector * vec)
Copies a vector, but not the data. Make sure you free it!
Definition at line 62 of file vector.c.
References DSVector::capacity, DSVector::data, ds_vector_append(), ds_vector_create_capacity(), and DSVector::size.
struct DSVector* ds_vector_create ()
Creates a vector with DS_VECTOR_BASE_CAPACITY. ds_vector_free or ds_vector_free_no_data will need to be called when done with the vector to avoid memory leaks.
Definition at line 21 of file vector.c.
References ds_vector_create_capacity().
Referenced by ds_hashmap_create().
struct DSVector* ds_vector_create_capacity (int32_t capacity)
Creates a vector with the given capacity. (N.B. This vector will still automatically increase in size if necessary.)
Definition at line 27 of file vector.c.
References DSVector::capacity, DSVector::data, and DSVector::size.
Referenced by ds_vector_copy(), and ds_vector_create().
int32_t ds_vector_find (struct DSVector * vec, void * needle, int32_t(compare)(void *, void *))
Higher-order function to find the first element in the vector such that compare(needle, element) == 0. Where compare is defined as: compare(a, b) < 0 when a < b compare(a, b) = 0 when a = b compare(a, b) > 0 when a > b
Returns an unsigned -1 if needle is not found.
Definition at line 154 of file vector.c.
References DSVector::data, and DSVector::size.
void ds_vector_free (struct DSVector * vec)
Free's a vector AND its data.
Definition at line 43 of file vector.c.
References DSVector::data, and DSVector::size.
void ds_vector_free_no_data (struct DSVector * vec)
Free's just the vector's representation. Data is NOT freed.
Definition at line 55 of file vector.c.
References DSVector::data.
Referenced by ds_hashmap_free().
void* ds_vector_get (struct DSVector * vec, int32_t index)
Gets an element at index i from a vector.
Definition at line 114 of file vector.c.
References DSVector::data, and DSVector::size.
Referenced by ds_hashmap_foreach_value(), ds_hashmap_foreach_valueAction(), ds_hashmap_print_keys(), ds_hashmap_print_keyvals(), and ds_hashmap_remove_int().
void ds_vector_insert (struct DSVector * vec, void * data, int32_t index)
Places an element at index i, and shifts the rest of the vector to the right by one. If index == size of vector, then the element will be appended to the end of the vector.
Definition at line 82 of file vector.c.
References DSVector::data, and DSVector::size.
void ds_vector_map (struct DSVector * vec, void(func)(void *))
Higher-order function to map func over every element in vector.
Definition at line 145 of file vector.c.
References DSVector::data, and DSVector::size.
void ds_vector_remove (struct DSVector * vec, int32_t index)
Removes an element from the vector at some index. Also shifts everything to right of index to the left. Does NOT free the data.
Definition at line 101 of file vector.c.
References DSVector::data, and DSVector::size.
Referenced by ds_hashmap_remove_int().
void ds_vector_set (struct DSVector * vec, void * data, int32_t index)
Sets an elements at index to data. No data is freed.
Definition at line 123 of file vector.c.
References DSVector::data, and DSVector::size.
void ds_vector_sort (struct DSVector * vec, int32_t(compare)(void *, void *))
I've implemented my own Quicksort (based on the Wikipedia entry on Quicksort) because I didn't like how the standard library's version of qsort forces you to define the comparison function. (Namely, that the arguments are void** instead of void*.)
Definition at line 173 of file vector.c.
References DSVector::capacity, DSVector::data, and DSVector::size.
Referenced by ds_hashmap_sort_by().
void ds_vector_swap (struct DSVector * vec, int32_t i, int32_t j)
Swaps the data from vector element i to vector element j.
Definition at line 132 of file vector.c.
References DSVector::data, and DSVector::size.