backEnd_src/whatDownBackEndApp.h File Reference
the front file for WhatDown Chat App back end (server side).
#include `defines.h`
*
Macros
#define SERVER_PORT 4848
#define SERVER_IP NULL
#define SERVER_MAX_CONNECTION 1000
#define SERVER_TIMOUT_MS 60000
#define CHAT_FIRSET_IP `225.1.1.1`
#define CHAT_MAX_NUM_IP 100
#define CHAT_PORT 2255
Typedefs
typedef struct WhatDownBackEndApp WhatDownBackEndApp_t
Functions
WhatDownBackEndApp_t * WhatDownBackEndApp_Create ()
create and setup the app server
void WhatDownBackEndApp_Destroy (WhatDownBackEndApp_t *_appBE)
cleans up after the app
bool WhatDownBackEndApp_Run (WhatDownBackEndApp_t *_appBE)
activate the server and start waiting for request. run a infinite loop until stop is called.
bool WhatDownBackEndApp_Stop (WhatDownBackEndApp_t *_appBE)
ask to stop the server. there might be a delay between request to full stop/
Detailed Description
the front file for WhatDown Chat App back end (server side).
Date
Jul 15, 2017
Author
Yuval Hamberg
Macro Definition Documentation
#define CHAT_FIRSET_IP `225.1.1.1`
Definition at line 22 of file whatDownBackEndApp.h.
Referenced by WhatDownBackEndApp_Create().
#define CHAT_MAX_NUM_IP 100
Definition at line 23 of file whatDownBackEndApp.h.
Referenced by WhatDownBackEndApp_Create().
#define CHAT_PORT 2255
Definition at line 24 of file whatDownBackEndApp.h.
Referenced by WhatDownBackEndApp_Create().
#define SERVER_IP NULL
Definition at line 18 of file whatDownBackEndApp.h.
Referenced by WhatDownBackEndApp_Create().
#define SERVER_MAX_CONNECTION 1000
Definition at line 19 of file whatDownBackEndApp.h.
Referenced by WhatDownBackEndApp_Create().
#define SERVER_PORT 4848
Definition at line 17 of file whatDownBackEndApp.h.
Referenced by WhatDownBackEndApp_Create().
#define SERVER_TIMOUT_MS 60000
Definition at line 20 of file whatDownBackEndApp.h.
Referenced by WhatDownBackEndApp_Create().
Typedef Documentation
typedef struct WhatDownBackEndApp WhatDownBackEndApp_t
Definition at line 30 of file whatDownBackEndApp.h.
Function Documentation
WhatDownBackEndApp_t* WhatDownBackEndApp_Create ()
create and setup the app server
Returns
pointer to the struct created
Definition at line 41 of file whatDownBackEndApp.c.
References CHAT_FIRSET_IP, CHAT_MAX_NUM_IP, CHAT_PORT, GroupsHandel_Create(), GroupsHandel_Destroy(), IP_Handle_Create(), IP_Handle_Destory(), LogicBE_ClientDissconnectedFunc(), LogicBE_Create(), LogicBE_Destroy(), LogicBE_ErrorFunc(), LogicBE_NewClientFunc(), LogicBE_ReciveDataFunc(), LogicBE_SetServerPTR(), WhatDownBackEndApp::m_BElogicPtr, WhatDownBackEndApp::m_groupsHndlPtr, WhatDownBackEndApp::m_ipHndlPtr, WhatDownBackEndApp::m_magicNumber, WhatDownBackEndApp::m_TCPnet, WhatDownBackEndApp::m_usersHandlePtr, MAGIC_NUMBER_ALIVE_BE_APP, SERVER_IP, SERVER_MAX_CONNECTION, SERVER_PORT, SERVER_TIMOUT_MS, TCP_CreateServer(), UsersHandle_Create(), and UsersHandle_Destroy().
Referenced by main().
void WhatDownBackEndApp_Destroy (WhatDownBackEndApp_t * _appBE)
cleans up after the app
Parameters
_appBE the struct
Definition at line 108 of file whatDownBackEndApp.c.
References GroupsHandel_Destroy(), IP_Handle_Destory(), IsStructValid(), LogicBE_Destroy(), WhatDownBackEndApp::m_BElogicPtr, WhatDownBackEndApp::m_groupsHndlPtr, WhatDownBackEndApp::m_ipHndlPtr, WhatDownBackEndApp::m_magicNumber, WhatDownBackEndApp::m_TCPnet, WhatDownBackEndApp::m_usersHandlePtr, TCP_DestroyServer(), and UsersHandle_Destroy().
Referenced by main().
bool WhatDownBackEndApp_Run (WhatDownBackEndApp_t * _appBE)
activate the server and start waiting for request. run a infinite loop until stop is called.
Parameters
_appBE the struct
Returns
TRUE when asked to stop and return. FALSE when returned out of error.
Definition at line 128 of file whatDownBackEndApp.c.
References FALSE, IsStructValid(), WhatDownBackEndApp::m_TCPnet, and TCP_RunServer().
Referenced by main().
bool WhatDownBackEndApp_Stop (WhatDownBackEndApp_t * _appBE)
ask to stop the server. there might be a delay between request to full stop/
Parameters
_appBE the struct
Returns
TRUE when asked to stop and return. FALSE when returned out of error.
Definition at line 138 of file whatDownBackEndApp.c.
References FALSE, IsStructValid(), WhatDownBackEndApp::m_magicNumber, WhatDownBackEndApp::m_TCPnet, MAGIC_NUMBER_ALIVE_BE_APP, and TCP_StopServer().