backEnd_src/whatDownBackEndApp.c File Reference
#include `whatDownBackEndApp.h`
*
#include `logic_backEnd.h`
*
#include `usersHandle.h`
*
#include `ipHandle.h`
*
#include `groupsHandle.h`
*
Data Structures
struct WhatDownBackEndApp
Macros
#define MAGIC_NUMBER_ALIVE_BE_APP 0xfadefade
Typedefs
typedef int bool
Functions
WhatDownBackEndApp_t * WhatDownBackEndApp_Create ()
create and setup the app server
void WhatDownBackEndApp_Destroy (WhatDownBackEndApp_t *_appBE)
cleans up after the app
bool WhatDownBackEndApp_Run (WhatDownBackEndApp_t *_appBE)
activate the server and start waiting for request. run a infinite loop until stop is called.
bool WhatDownBackEndApp_Stop (WhatDownBackEndApp_t *_appBE)
ask to stop the server. there might be a delay between request to full stop/
Macro Definition Documentation
#define MAGIC_NUMBER_ALIVE_BE_APP 0xfadefade
Definition at line 16 of file whatDownBackEndApp.c.
Referenced by WhatDownBackEndApp_Create(), and WhatDownBackEndApp_Stop().
Typedef Documentation
typedef int bool
Definition at line 18 of file whatDownBackEndApp.c.
Function Documentation
WhatDownBackEndApp_t* WhatDownBackEndApp_Create ()
create and setup the app server
Returns
pointer to the struct created
Definition at line 41 of file whatDownBackEndApp.c.
References CHAT_FIRSET_IP, CHAT_MAX_NUM_IP, CHAT_PORT, GroupsHandel_Create(), GroupsHandel_Destroy(), IP_Handle_Create(), IP_Handle_Destory(), LogicBE_ClientDissconnectedFunc(), LogicBE_Create(), LogicBE_Destroy(), LogicBE_ErrorFunc(), LogicBE_NewClientFunc(), LogicBE_ReciveDataFunc(), LogicBE_SetServerPTR(), WhatDownBackEndApp::m_BElogicPtr, WhatDownBackEndApp::m_groupsHndlPtr, WhatDownBackEndApp::m_ipHndlPtr, WhatDownBackEndApp::m_magicNumber, WhatDownBackEndApp::m_TCPnet, WhatDownBackEndApp::m_usersHandlePtr, MAGIC_NUMBER_ALIVE_BE_APP, SERVER_IP, SERVER_MAX_CONNECTION, SERVER_PORT, SERVER_TIMOUT_MS, TCP_CreateServer(), UsersHandle_Create(), and UsersHandle_Destroy().
Referenced by main().
void WhatDownBackEndApp_Destroy (WhatDownBackEndApp_t * _appBE)
cleans up after the app
Parameters
_appBE the struct
Definition at line 108 of file whatDownBackEndApp.c.
References GroupsHandel_Destroy(), IP_Handle_Destory(), IsStructValid(), LogicBE_Destroy(), WhatDownBackEndApp::m_BElogicPtr, WhatDownBackEndApp::m_groupsHndlPtr, WhatDownBackEndApp::m_ipHndlPtr, WhatDownBackEndApp::m_magicNumber, WhatDownBackEndApp::m_TCPnet, WhatDownBackEndApp::m_usersHandlePtr, TCP_DestroyServer(), and UsersHandle_Destroy().
Referenced by main().
bool WhatDownBackEndApp_Run (WhatDownBackEndApp_t * _appBE)
activate the server and start waiting for request. run a infinite loop until stop is called.
Parameters
_appBE the struct
Returns
TRUE when asked to stop and return. FALSE when returned out of error.
Definition at line 128 of file whatDownBackEndApp.c.
References FALSE, IsStructValid(), WhatDownBackEndApp::m_TCPnet, and TCP_RunServer().
Referenced by main().
bool WhatDownBackEndApp_Stop (WhatDownBackEndApp_t * _appBE)
ask to stop the server. there might be a delay between request to full stop/
Parameters
_appBE the struct
Returns
TRUE when asked to stop and return. FALSE when returned out of error.
Definition at line 138 of file whatDownBackEndApp.c.
References FALSE, IsStructValid(), WhatDownBackEndApp::m_magicNumber, WhatDownBackEndApp::m_TCPnet, MAGIC_NUMBER_ALIVE_BE_APP, and TCP_StopServer().